### PR TITLE
Update to v9.5.0-IOFreeze

### LINKED ISSUE #4210: Update to EnergyPlus 9.5.0
Enhancement Request
--------------

Once v9.5.0-IOFreeze is released, we should update to it.

## Detailed Description

https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/InputRulesFiles/Rules9-4-0-to-9-5-0.md

### New additions
- [x] ASTM C1340 convection algorithm https://github.com/NREL/EnergyPlus/pull/8518
- [ ] `ElectricLoadCenter:Storage:LiIonNMCBattery`: New battery model from SAM https://github.com/NREL/EnergyPlus/pull/8499
     * Specific PR opened for this on https://github.com/NREL/OpenStudio/issues/4223

### Minor stuff

- [x] Fields have been removed on `Construction:AirBoundary` https://github.com/NREL/EnergyPlus/pull/8370
- [x] Additional fuel types for Generator:*Turbine objects https://github.com/NREL/EnergyPlus/pull/8413
- [x] EquationFit coil changes and new Curve object https://github.com/NREL/EnergyPlus/pull/8464

### LINKED ISSUE #4224: E+ 9.5.0: wrap new field `Allow Unsupported Zone Equipment` (and `Solver`) for AirflowNetwork:SimulationControl
Enhancement Request
--------------

E+ 9.5.0: wrap new field `Allow Unsupported Zone Equipment` (and `Solver`) for AirflowNetwork:SimulationControl

### LINKED ISSUE #4227: E+: Wrap object Curve:QuadLinear
Enhancement Request
--------------

E+: Wrap object `Curve:QuadLinear`. It's been around since at least version 9.0 but wasn't really used until now (`Coil:Cooling:WaterToAirHeatPump:EquationFit`)

### LINKED ISSUE #4228: E+ 9.5.0: Wrap new object Curve:QuintLinear
Enhancement Request
--------------
E+ 9.5.0: Wrap new object `Curve:QuintLinear` (used in `Coil:Cooling:WaterToAirHeatPump:EquationFit`)

### LINKED ISSUE #4229: E+ 9.5.0: make changes to the EquationFit coils that got curves instead of harcoded coefficients
Enhancement Request
--------------

https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/InputRulesFiles/Rules9-4-0-to-9-5-0.md#object-change-coilheatingwatertoairheatpumpequationfit

```
Coil:Cooling:WaterToAirHeatPump:EquationFit
Coil:Heating:WaterToAirHeatPump:EquationFit
HeatPump:WaterToWater:EquationFit:Heating
HeatPump:WaterToWater:EquationFit:Cooling
```

Backward-compatible API methods will be provided

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4210
 - Fix #4227
 - Fix #4228
 - Fix #4224
 - Fix #4229

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [x] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [x] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [x] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [x] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
OpenStudio-resources tests results with https://github.com/NREL/OpenStudio/pull/4212/commits/5778092d577093e1665833351ba1701d03c8ee20

image

----

**Comment by jmarrec** [comment]
bundle_git is still failing.

```
(py39)julien@OpenStudio-resources (v9.5.0-IOFreeze *)$ $os_build_rel/Products/openstudio model_tests.rb -n /model_articulation1_bundle_git/
Setting ENV['N'] = 11

# Running tests with run options :

Running for OpenStudio 3.1.1-alpha+e647df90d3
Running for OpenStudio 3.1.1-alpha+e647df90d3 (Previous=3.1.0)

# Running tests with run options -n /model_articulation1_bundle_git/ --seed 54750:

[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path './gems'`, and stop using this flag
Fetching https://github.com/nrel/openstudio-workflow-gem.git
Fetching gem metadata from http://rubygems.org/
Resolving dependencies...
Using bundler 2.1.4
Using openstudio-workflow 2.2.0 from https://github.com/nrel/openstudio-workflow-gem.git (at v2.2.0@e5a8f7f)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./gems`
Writing lockfile to /home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile.lock
E

Finished tests in 7.686816s, 0.1301 tests/s, 0.2602 assertions/s.


Error:
ModelTests#test_model_articulation1_bundle_git_osw:
RuntimeError: Exit code 1:
Error executing argv: ["--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/gems", "run", "-w", "/home/julien/Software/Others/OpenStudio-resources/testruns/model_articulation1_bundle_git.osw/in.osw"]
Error: undefined method `from_stub' for nil:NilClass in :/ruby/2.7.0/bundler/source/git.rb:322:in `load_gemspec'
:/ruby/2.7.0/bundler/source/path.rb:173:in `block in load_spec_files'
:/ruby/2.7.0/bundler/source/path.rb:172:in `each'
:/ruby/2.7.0/bundler/source/path.rb:172:in `load_spec_files'
:/ruby/2.7.0/bundler/source/git.rb:203:in `load_spec_files'
:/ruby/2.7.0/bundler/source/path.rb:107:in `local_specs'
:/ruby/2.7.0/bundler/source/git.rb:170:in `specs'
:/ruby/2.7.0/bundler/lazy_specification.rb:75:in `__materialize__'
:/ruby/2.7.0/bundler/spec_set.rb:83:in `block in materialize'
:/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
:/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
:/ruby/2.7.0/bundler/definition.rb:170:in `specs'
:/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
:/openstudio_cli.rb:637:in `parse_main_args'
:/openstudio_cli.rb:766:in `execute'
:/openstudio_cli.rb:1796:in `<main>'
eval:177:in `eval'
eval:177:in `require_embedded_absolute'
eval:162:in `block in require_embedded'
eval:156:in `each'
eval:156:in `require_embedded'
eval:115:in `require'
eval:3:in `<main>'

    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:346:in `block in run_command'
    :/ruby/2.7.0/open3.rb:219:in `popen_run'
    :/ruby/2.7.0/open3.rb:101:in `popen3'
    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:334:in `run_command'
    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:682:in `sim_test'
    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:1204:in `test_model_articulation1_bundle_git_osw'

1 tests, 2 assertions, 0 failures, 1 errors, 0 skips
```

@tijcolem Have you tried this test with 2.7.2 recently?

**Comment by jmarrec** [comment]
* [ ] autosize_hvac.rb

eplusout.err

```
   **  Fatal  ** SimLowTempRadiantSystem: Unit not found=ZONE HVAC LOW TEMPERATURE RADIANT VARIABLE FLOW 
```

A cursory look at the IDF file reveals zero problems... The objects are there. The LowTemp object is on a cooling and heating branch, and in a ZoneHVAC:EquipmentList...

```
ZoneHVAC:LowTemperatureRadiant:VariableFlow,
  Zone HVAC Low Temperature Radiant Variable Flow 1, !- Name
  Zone HVAC Low Temperature Radiant Variable Flow 1 Design, !- Design Object
  Always On Discrete,                     !- Availability Schedule Name
  Story 4 Core Thermal Zone,              !- Zone Name
  Zone HVAC Low Temperature Radiant Variable Flow 1Floors, !- Surface Name or Radiant Surface Group Name
  Autosize,                               !- Hydronic Tubing Length {m}
  Autosize,                               !- Heating Design Capacity {W}
  Autosize,                               !- Maximum Hot Water Flow {m3/s}
  Node 276,                               !- Heating Water Inlet Node Name
  Node 277,                               !- Heating Water Outlet Node Name
  Autosize,                               !- Cooling Design Capacity {W}
  Autosize,                               !- Maximum Cold Water Flow {m3/s}
  Node 278,                               !- Cooling Water Inlet Node Name
  Node 279,                               !- Cooling Water Outlet Node Name
  OnePerSurface,                          !- Number of Circuits
  106.7;                                  !- Circuit Length {m}

ZoneHVAC:LowTemperatureRadiant:VariableFlow:Design,
  Zone HVAC Low Temperature Radiant Variable Flow 1 Design, !- Name
  ConvectionOnly,                         !- Fluid to Radiant Surface Heat Transfer Model
  0.013,                                  !- Hydronic Tubing Inside Diameter {m}
  0.016,                                  !- Hydronic Tubing Outside Diameter {m}
  0.35,                                   !- Hydronic Tubing Conductivity {W/m-K}
  MeanAirTemperature,                     !- Temperature Control Type
  HalfFlowPower,                          !- Setpoint Control Type
  HeatingDesignCapacity,                  !- Heating Design Capacity Method
  0,                                      !- Heating Design Capacity Per Floor Area {W/m2}
  1,                                      !- Fraction of Autosized Heating Design Capacity
  0.5,                                    !- Heating Control Throttling Range {deltaC}
  Schedule Constant 3,                    !- Heating Control Temperature Schedule Name
  CoolingDesignCapacity,                  !- Cooling Design Capacity Method
  0,                                      !- Cooling Design Capacity Per Floor Area {W/m2}
  1,                                      !- Fraction of Autosized Cooling Design Capacity
  0.5,                                    !- Cooling Control Throttling Range {deltaC}
  Schedule Constant 4,                    !- Cooling Control Temperature Schedule Name
  SimpleOff,                              !- Condensation Control Type
  1;                                      !- Condensation Control Dewpoint Offset {C}

ZoneHVAC:LowTemperatureRadiant:SurfaceGroup,
  Zone HVAC Low Temperature Radiant Variable Flow 1Floors, !- Name
  Surface 115,                            !- Surface Name 1
  1;                                      !- Flow Fraction for Surface 1
```

I will investigate a bit to see if this is an OS problem or an E+ one


https://github.com/NREL/EnergyPlus/blob/e003a916370b9bc68fa60e39e504bd8b2ae52ca9/src/EnergyPlus/LowTempRadiantSystem.cc#L290

```
* thread #1, name = 'energyplus', stop reason = breakpoint 1.1
    frame #0: 0x00007fffef3854d5 libenergyplusapi.so.9.5.0`EnergyPlus::LowTempRadiantSystem::SimLowTempRadiantSystem(state=0x00007fffffffb890, CompName="ZONE HVAC LOW TEMPERATURE RADIANT VARIABLE FLOW 1", FirstHVACIteration=true, LoadMet=0x00007fffffffb0b0, CompIndex=0x00005555573eb600) at LowTempRadiantSystem.cc:290:56
   287 	
   288 	        // Find the correct Low Temp Radiant System
   289 	        if (CompIndex == 0) {
-> 290 	            RadSysNum = UtilityRoutines::FindItemInList(CompName, RadSysTypes);
   291 	            if (RadSysNum == 0) {
   292 	                ShowFatalError(state, "SimLowTempRadiantSystem: Unit not found=" + CompName);
   293 	            }
(lldb) p CompName
(const std::string) $5 = "ZONE HVAC LOW TEMPERATURE RADIANT VARIABLE FLOW 1"
(lldb) p RadSysTypes(1)
(EnergyPlus::LowTempRadiantSystem::RadSysTypeData) $6 = (Name = "ZONE HVAC LOW TEMPERATURE RADIANT CONSTANT FLOW 1", SystemType = ConstantFlowSystem, CompIndex = 0)
(lldb) p RadSysTypes(2)
(EnergyPlus::LowTempRadiantSystem::RadSysTypeData) $7 = (Name = "ZONE HVAC LOW TEMPERATURE RADIANT ELECTRIC 1", SystemType = ElectricSystem, CompIndex = 1)
(lldb) p RadSysTypes(3)
(EnergyPlus::LowTempRadiantSystem::RadSysTypeData) $8 = (Name = "", SystemType = Unassigned, CompIndex = 0)
```

Smell like an E+ problem...

**Comment by jmarrec** [comment]
Current status:

image

The Fan:ZoneExhaust deviation is very concerning too:

image

**Comment by jmarrec** [comment]
I fixed the autosize_hvac stuff. Down to the model_articulation1_bundle_git one, which I opened a specific issue on https://github.com/NREL/OpenStudio-resources/issues/134 @tijcolem 


image

**Comment by kbenne** [comment]
@jmarrec are you ready to merge this and move develop forward? From your report it looks like the zone hvac autosize failure is not a regression due to the 9.5 update.

**Comment by jmarrec** [comment]
@kbenne I think it's ready to be reviewed and merged yes

**Comment by kbenne** [comment]
alright. we talked at scrum a few minutes ago, and I'm going to try to get as many PRs merged that are not related to 9.5, and then I'll merge this.

**Pull request merged**
