### PR TITLE
Chiller:Electric:EIR node API refactor, ChillerAbsorption/ChillerAbsorption tertiary node refactor

### LINKED ISSUE #3111: ChillerAbsorption is missing implementation of tertiary nodes for Generator Loop
`ChillerAbsorption` doesn't have tertiary nodes implemented to be able to connect the Generator loop. Connecting the Chilled Water and Condenser loop is now possible, but not the generator.

A very similar object, `ChillerAbsorptionIndirect` does have these connections defined (see [here](https://github.com/NREL/OpenStudio/blob/8de135fac78eda3b58b8381aac1f966e2c4c3186/openstudiocore/src/model/ChillerAbsorptionIndirect_Impl.hpp#L75)), and there is no override of the `addToNode` nor `addToTertiaryNode` methods currently.

After implementing the tertiaryInletPort and tertiaryOutletPort for `ChillerAbsorption`, in both `ChillerAbsorption` and `ChillerAbsorptionIndirect` I suggest overwriting the `addToNode` and `addToTertiaryNode` like I did in CentralHeatPumpSystem so that it'll work in the OS App. 

Basically in the addToNode, you check if the object is trying to be connected to the ***demand** side of a plant loop, and its already connected to the ***condenser** water loop but without a tertiary loop, then you connect it to the tertiary loop. See docstrings https://github.com/NREL/OpenStudio/blob/8de135fac78eda3b58b8381aac1f966e2c4c3186/openstudiocore/src/model/CentralHeatPumpSystem_Impl.hpp#L86-L94  and actual implementation [here](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/CentralHeatPumpSystem.cpp#L194), 
and a note I left in 

https://github.com/NREL/OpenStudio/blob/8de135fac78eda3b58b8381aac1f966e2c4c3186/openstudiocore/src/openstudio_lib/HVACSystemsController.cpp#L600-L609

### LINKED ISSUE #3606: Chiller:Electric:EIR API related to node need a serious refactor
None of these should exist, especially not in the public header (`ChillerElectricEIR.hpp`):

```c++
  bool setChilledWaterInletNodeName(std::string chilledWaterInletNodeName);
  bool setChilledWaterOutletNodeName(std::string chilledWaterOutletNodeName);

  bool setCondenserInletNodeName(boost::optional<std::string> condenserInletNodeName);
  bool setCondenserInletNodeName(std::string condenserInletNodeName);
  void resetCondenserInletNodeName();

  bool setCondenserOutletNodeName(boost::optional<std::string> condenserOutletNodeName);
  bool setCondenserOutletNodeName(std::string condenserOutletNodeName);
  void resetCondenserOutletNodeName();

  bool setHeatRecoveryInletNodeName(boost::optional<std::string> heatRecoveryInletNodeName);
  bool setHeatRecoveryInletNodeName(std::string heatRecoveryInletNodeName);
  void resetHeatRecoveryInletNodeName();

  bool setHeatRecoveryOutletNodeName(boost::optional<std::string> heatRecoveryOutletNodeName);
  bool setHeatRecoveryOutletNodeName(std::string heatRecoveryOutletNodeName);
  void resetHeatRecoveryOutletNodeName();
```

All of these plant loop connections are supposed to be set using addToNode / addToTertiaryNode.

ChillerElectricEIR::addToNode should probably be overloaded to do something like what I've done for CentralHeatPumpSystem:

https://github.com/NREL/OpenStudio/blob/5dc8c4e966066dcbeffddfb0ae1f9a65d84536c5/src/model/CentralHeatPumpSystem.cpp#L194-L221

@eringold can give you a MCVE of a ruby script that produces a hard crash

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fixes #3606: Refactor `Chiller:Electric:EIR` API related to node: no getter/setter to manipulate nodes by name.
 - Fixes #3111: Add tertiary node for `ChillerAbsoprtion`

- For `ChillerAbsoprtion`, `ChillerAbsoprtionIndirect`, `Chiller:Electric:EIR`:
    - addToTertiaryNode overriden to only allow demand side
    - addToNode overriden to connect to tertiary loop if secondary (condenser Loop) is already connected, node to connect to is on the demand side of a different plant loop than the current condenser loop
    - For the Absorption chillers, connection to tertiary loop Switch Generator Heat Source Type to "HotWater", and back to "Steam" when disconnecting

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [x] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [x] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [x] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
@kbenne Still working on this one

**Comment by jmarrec** [comment]
@kbenne Ok, ready for review I think.

**Comment by kbenne** [comment]
@jmarrec did you or can you add one or more simulation tests to demonstrate this feature?

**Comment by jmarrec** [comment]
@kbenne https://github.com/NREL/OpenStudio-resources/pull/97. A good idea to have done that, I realized I completely messed it up: all three chillers should have tertiary = DEMAND side of another loop, not supply:
* For ChillerAbsorption, ChillerAbsorptionIndirect: this is the generator loop (Hot water loop (or steam, but not in OS)), so it should logically be on the demand side of that one. No problem here.
* For ChillerElectricEIR, it's way trickier... 
    * But given that the chiller isn't "active" in terms of responding to any loop on the HR loop, I think it makes more sense on the demand side
    * There are no example files with a ChillerElectricEIR with HR, but Chiller:EngineDriven, and that's on the demand side
   * It seems that I found a tiny sentence in the engineering reference guide after all that seem to indicate demand side... cf [here](https://bigladdersoftware.com/epx/docs/9-2/engineering-reference/chillers.html#hot-water-heat-recovery-from-chillers)
    *  > Note that the heat recovery side of the chiller is placed on the demand-side of a heat recovery loop which will typically supply a hot water storage tank.
    * **But** E+ will let your file run if you put it on the supply side of the Heat Recovery Loop... 
    * So that seems akin to https://github.com/NREL/EnergyPlus/issues/7735 (Placement of solar collectors)
    * **In the end until proven otherwise, I have chosen to limit connection to the DEMAND side of the Heat Recovery Loop*

**Pull request merged**
