### PR TITLE
Fixed an issue in Surface splitSurfaceForSubSurfaces which caused the…

### PR DESCRIPTION
**Pull request by ggartside**
…w routine to return way too may overlapping surfaces

Added a unit test Issue_4374 which uses one surface from the secondary school ref building as test dats

Pull request overview
---------------------

 - Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by tijcolem** [comment]
@ggartside This is great as this is an important fix. 

@DavidGoldwasser Would you be able to use one of the installers to verify this fixes the problem?

**Comment by DavidGoldwasser** [comment]
Not working yet, see my updates on this issue in measure repo. 
https://github.com/NREL/openstudio-model-articulation-gem/issues/76#issuecomment-927178641

**Comment by DavidGoldwasser** [comment]
@ggartside ok, so I think we are good with what was in this installer without the new proposed change to change where the split happens. This was misunderstanding on my part. I didn't realize it splits between all sub-surfaces instead of just doors. Here are my proposed fixes to the measure. One removes windows before splitting so it only splits at doors. The other is change in tolerance on rectangle check. https://github.com/NREL/openstudio-model-articulation-gem/commit/3769173f610d2de25374813be9f06be5a156b9a9

**Comment by DavidGoldwasser** [comment]
@ggartside and @tijcolem minor correction to my last comment. I'm using ins taller from a few days ago, I'm wondering if the last commit from today should be removed? or maybe it won't create any problems. I'm concerned that when I do clear out windows before split that the new split won't be tight against the door as is expected.
https://github.com/NREL/OpenStudio/pull/4431/commits/7035a3edf9aede060b50039ffc68244c6cfdc473

**Comment by tijcolem** [comment]
@ggartside Sounds like @DavidGoldwasser was able to successfully use your split surface fix ending on commit 
https://github.com/NREL/OpenStudio/pull/4431/commits/42398b6f5a84b0efc9103bf1a48b291bacb537d0 in this branch. Since this is working, it's probably best to revert to that commit.  You don't need to do force push as we can have a record of the other changes (maybe it'll still come into play).

**Comment by ggartside** [comment]
@DavidGoldwasser If the intention is to only split the surface around doors then I could modify the original routine to skip window openings. 

@tijcolem I will revert back to the original method, 

One thing I don't understand yet is why this routine is necessary, maybe you can enlighten me?

**Comment by DavidGoldwasser** [comment]
Task linked: [CU-1h1w527 Review Surface matching PR (03)](https://app.clickup.com/t/1h1w527)

**Comment by tijcolem** [comment]
@ggartside Thanks for reverting!  This looks good and I'll drop in.

**Pull request merged**
