### PR TITLE
Improve performance of HVAC object creation

### PR DESCRIPTION
**Pull request by mbadams5**
These improvements stemmed from a conversation on Unmethours slack about the time to create models programmatically with a large number of zones.
#### User's graph showing the time to create a new subsequent (HVAC) object.
pasted image at 2016_12_14 03_56 pm

This really starts to show the DFS traversal cost as more and more objects are added.

This PR begins to address this concern and improves the performance for programmatic creation of large models.

Overall the performance goes from 484 seconds to 164 seconds, or a 66% reduction, for the test program (see below).

The graphs below show the improvement to create each subsequent object. The log-log graphs shows that the underlying time complexity hasn't changed, and under future work I hope to see if this is addressable but I am not certain.

combined
loglog

```python
import time
from openstudio import model
import time
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')

m = model.Model()
chw_plant_loop = model.PlantLoop(m)
hhw_plant_loop = model.PlantLoop(m)
air_loop = model.AirLoopHVAC(m)
availability_schedule = model.ScheduleConstant(m)

start = time.time()

time_array = []
iterations = range(0, 500)
for i in iterations:
    st = time.time()

    zone = model.ThermalZone(m)

    coil = model.CoilHeatingWater(m, availability_schedule)
    new_terminal = model.AirTerminalSingleDuctConstantVolumeReheat(m, availability_schedule, coil)
    air_loop.addBranchForZone(zone, new_terminal)

    hhw_plant_loop.addDemandBranchForComponent(coil)

    coil_heating = model.CoilHeatingWater(m, availability_schedule)
    hhw_plant_loop.addDemandBranchForComponent(coil_heating)
    coil_cooling = model.CoilCoolingWater(m, availability_schedule)
    chw_plant_loop.addDemandBranchForComponent(coil_cooling)
    fan = model.FanVariableVolume(m, availability_schedule)
    zone_hvac = model.ZoneHVACFourPipeFanCoil(m, availability_schedule, fan, coil_cooling, coil_heating)
    zone_hvac.addToThermalZone(zone)
    et = time.time()
    time_array.append(et-st)

plt.plot(iterations, time_array, )
plt.savefig('figure.png')

end = time.time()
print("total time = %s" % (end - start))
```

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by macumber** [comment]
@kbenne can we get this into the June release?  Would running the regression tests against this branch be sufficient for testing?

**Comment by macumber** [comment]
@mbadams5 fyi there are a lot of line ending diffs in here :-/

**Comment by mbadams5** [comment]
@macumber what line ending diffs? There are a lot of whitespace removal diffs, which were removed by my text editor automatically. You can see it without diffs on Github with `?w=1` at the end of the url.

**Comment by mbadams5** [comment]
@kbenne Does this need a version translation to add the mixers and splitters to the PlantLoop and AirLoopHVAC for old OSMs?

**Comment by macumber** [comment]
Yeah you are right, I just meant whitespace changes, looking at [this diff](https://github.com/NREL/OpenStudio/pull/2550/files?w=1) is way cleaner, thanks!

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @mbadams5 @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
