### PR TITLE
Changes to work with CMake 3.4, not sure if this is backwards compatible

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@axelstudios @evanweaver can you take a look and see if this works for your versions of cmake?

**Comment by axelstudios** [comment]
Which OS do these changes target?  Windows?  I was able to use 3.4 with mac (didn't test packaging) fine with no warnings.

**Comment by macumber** [comment]
To be honest I'm not all that sure about this one, it looks like both CheckIncludeFile and CheckIncludeFiles are in 3.4, for some reason I was not able to configure with it as it was, this shouldn't get merged without more info

https://cmake.org/cmake/help/v3.4/module/CheckIncludeFile.html

https://cmake.org/cmake/help/v3.4/module/CheckIncludeFiles.html

**Comment by kbenne** [comment]
I keep having to do this locally to get my builds to work. I'd say merge.

**Comment by macumber** [comment]
Do you understand why?  I can't figure out what breaking change happened?

**Comment by axelstudios** [comment]
What warning do you get?  I've never seen this

**Comment by nrel-bot-2** [comment]
@axelstudios @macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@axelstudios @macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@axelstudios @macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by macumber** [comment]
Sounds like this is no longer necessary with latest cmake

**Pull request closed without merging**
