### PR TITLE
Add a PR template to avoid common mistakes / ommissions

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Run Unit Test(s) locally

### CODE REVIEW

**Comment by kbenne** [comment]
Run unit tests locally? isn't that what the robots are for?

**Comment by tijcolem** [comment]
Yes, I can do some research and find c++ linter options. This should be fairly straightforward to implement in our CI setup. I'll report back and summarize the linter options.

**Comment by Myoldmopar** [comment]
We have some intermittent luck with this, sometimes code seems to sneak through which shouldn't pass, but then other times it does warn about it.  You can take a look at the main checker script here: https://github.com/NREL/EnergyPlus/blob/develop/scripts/dev/verify_formatting.sh for more info.

**Comment by jmarrec** [comment]
>     * Run unit tests locally? isn't that what the robots are for? How about "Check that appropriate tests have been added"

This is a copy paste from the E+ one that I should have removed indeed.

**Comment by tijcolem** [comment]
We may want to have a separate CI pipeline to run the linter for PRs.  And this can probably be ran on every pr (don't need to label "Ready for CI") as it's probably an inexpensive operation on the CI machines. 

I think we should accept this PR to get a template in place and then open a separate issue regarding the linter.

**Comment by tijcolem** [comment]
adding https://github.com/NREL/OpenStudio/issues/3718

**Comment by jmarrec** [comment]
Addressed @kbenne 's comment.

**Pull request merged**
