### PR TITLE
Switching to QWebEngine if building with Qt >= 5.4

### PR DESCRIPTION
**Pull request by axelstudios**
I'm seeing a 2.8x performance increase for JavaScript, according to the SunSpider benchmark.  This should alleviate #1211 while remaining backwards-compatible.

### CODE REVIEW

**Comment by macumber** [comment]
@axelstudios what are the new dependencies for QWebEngine?  Kenny had to add a few things on Peregrine to support QWebKit, is QWebEngine easier/harder/or about the same to compile?

**Comment by axelstudios** [comment]
It should be nearly the same, possibly a couple more.  See the [fedora section](http://qt-project.org/wiki/QtWebEngineHowToTry)

**Comment by macumber** [comment]
@axelstudios are you done with this and ready for me to test?

**Comment by axelstudios** [comment]
Yeah, this is done.  Just be sure to install Qt 5.4.1 if you want it to actually use the WebEngine.

**Comment by macumber** [comment]
@axelstudios are the build machines updated with Qt 5.4.1?  Will this be used in the iteration packages tomorrow?

**Comment by axelstudios** [comment]
They aren't, but my windows/mac machines are.  I'll use them for the builds

**Pull request merged**
