### PR TITLE
Update embeddable_gbxml_editor.html to match new build from @theo-arm…

### LINKED ISSUE #3668: Update spider
Once Theo gets html working update spider gbXML viewer

### PR DESCRIPTION
**Pull request by macumber**
…our and @ladybug-tools/spiders, build available at:

https://github.com/ladybug-tools/spider-gbxml-viewers-for-openstudio/issues/2

Theo et. al. have done an amazing job to make this update as easy as can be, thank you all for your hard work!

Fixes #3668

## OpenStudio Pull Request Template

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStrudio Pull Request protocol.

### CODE REVIEW

**Comment by macumber** [comment]
@tijcolem @davidgoldwasser this should be easy to test, just need to get packages from ci, go to the geometry tab, instead of creating a new FloorspaceJS you want to select gbXML and then import a gbXML file.  @pflaumingo could provide some gbXML files for testing

**Comment by tijcolem** [comment]
David and I tested and used the gbxml files located in https://github.com/NREL/OpenStudio/tree/develop/openstudiocore/resources/gbxml and those loaded fine.  We did notice that https://github.com/NREL/openstudio-cli-demo/blob/master/common/files/gbXML_TRK.xml loaded, but wasn't displaying properly. 

Should this work with any gbxml type file?

**Comment by macumber** [comment]
Thanks @tijcolem !  Nice work @theo-armour!

**Comment by theo-armour** [comment]
@macumber @tijcolem 

I'm happy to hear that generally the embedding is progressing well.

gbXML_TRK.xml - as forked to the Spider repo - is a file I use very frequently for testing. So it should be OK.

I will look into the version in the NREL repo and check with latest SGV4OS and report back.

**Comment by theo-armour** [comment]
@macumber @tijcolem

I am reproducing the issue I think,

I am writing a script to make it easier to test the viewers on many files in many files more easily and quickly. Guess what? Issues are being found.

The script identifies up to 100 repos in a GitHub organization and lists all folders and files that with XML extension, Click the filename to see if it works in the Viewer.

[Spider gbXML Gallery for OpenStudio]( https://www.ladybug.tools/spider-gbxml-viewers-for-openstudio/sandbox/spider-gbxml-gallery/spider-gbxml-gallery.html )

image

Will fix the issues ASAP

**Comment by theo-armour** [comment]
@macumber @tijcolem

So here is what is happening: Long ago and far away a company named Autodesk decided that all their Revit files should be exported to gbXML in 16-bit format thus bringing joy to their users with twice as much file size for the same price.

An example

https://github.com/GreenBuildingXML/Sample_gbXML_Files/blob/master/gbXML_TRK.xml

Western browsers seem, however, to prefer the smaller 8-bit format. My parser currently barfs when looking at 16-bit files. v0.06.01 now displays an error message when given a 16-bit file

So neither Viewer r5.2 or v0.06.01 will read the above file as things now stand. But magic can happen - as shown here:

image

Workarounds

1. OpenStudio uses XMLHttpRequest instead of Fetch

* XMLHttpRequest seems to convert 16-bit ti 8-bit on the fly
* Fetch preserves the 16-bit format
* Can this be done inside of qtwebengine?

2. Use [Spider gbXML Viewer 'Maevia']( https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer )

* Open 16-bit file using Maevia. Saving will automagically convert to 8-bit
* Screen capture above is an example
 
3. There should be a way

* I am only a quarter-full stack developer, but there should be a way for viewers to convert the files on the fly using Uint8Array and Uint16Array.

***
1: might be nicest. 3: Can work on if I can get help. In the meantime maybe there should be a note somewhere.

***

## [Spider gbXML Viewer v0.0.06.01 for OpenStudio 2.9.0]( https://www.ladybug.tools/spider-gbxml-viewers-for-openstudio/spider-gbxml-viewer-for-openstudio-2-9-0/v-0-06-01/embeddable_gbxml_editor.html )

* Is up
* Adds more feedback if cannot read file
* Fixes error if a surface has no name

See read me and much more here:

## [Spider gbXML Viewers for OpenStudio]( https://www.ladybug.tools/spider-gbxml-viewers-for-openstudio/ )
 ***

## [Spider gbXML Gallery for OpenStudio ]( https://www.ladybug.tools/spider-gbxml-viewers-for-openstudio/sandbox/spider-gbxml-gallery/spider-gbxml-gallery.html )

* Lots of fun here
* Will add to Maevia somewhere
* Thanks for the impetus for doing this

**Pull request merged**
