### PR TITLE
Change default Idd filetype to EnergyPlus instead of OpenStudio for Workspace

### LINKED ISSUE #1538: Change default idd file type for Workspace.new
Apparently I have been living under a rock or something but I thought that Workspace.new made an EnergyPlus workspace.  It actually makes an OpenStudio one and has for some time:

https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/utilities/idf/Workspace.cpp#L2672

I think that most people calling Workspace.new want an EnergyPlus workspace, if they wanted an OpenStudio one they would make a model?

@DavidGoldwasser @asparke2 @kbenne you guys have thoughts?

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #1538

### CODE REVIEW

**Comment by jmarrec** [comment]
All GTests pass. Hopefully I caught every location where changes was needed.

**Comment by macumber** [comment]
Let's wait on this one until after code freeze

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
