### PR TITLE
misc updates copied from measure repo

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
Earlier commit changed uuid in xml. This changes it back. Also has commit to fix test models that were corrupt, shift over zone temp condition heat map colors, and swap heating and cooling setpoint for air loop summary. Tested locally. I'll wait to merge until I see if all builds work here.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@macumber any thoughts why I can build this on my machine, but fails with nrel-bot? All I changed was the standard reporting measure.

**Comment by macumber** [comment]
The CI machines are not working, I thought @evanweaver might have said something this morning about fixing them?

**Comment by DavidGoldwasser** [comment]
I can hold of on merging this until closer to the next iteration.

**Comment by evanweaver** [comment]
@macumber, this is new territory for me. I need to get up to speed, learn the details, before I can effect a fix.

In the meantime @DavidGoldwasser, thank you for being vigilant and heading the bot warnings. That said, for the time being, check "Details" above and you will see that the only complaint is about CMakeLists. For now, this single warning can be ignored. This branch is good to merge now.

**Pull request merged**
