### PR TITLE
1682 waterheater stratified

### LINKED ISSUE #1682: Add support of WaterHeater:Stratified

### PR DESCRIPTION
**Pull request by mbadams5**
This adds WaterHeater:Stratified to OpenStudio.

Fixes #1682 
[Delivers #97920112]

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Good work guys; I'll merge it now.  :no_entry_sign:  Hmm...what?  No write access for me..... probably for the best :wink: 

OK, in seriousness thanks for getting this underway @mbadams5, I'll update my TPEx translators accordingly so they are ready for this to go mainstream.

**Comment by Myoldmopar** [comment]
@kbenne @mbadams5  I'm planning out a few tasks and I don't want to work on the HPWH translator again until we have a release version of OS with that capability.  What release do you anticipate this being included with?  Also, can I use a preposition to end a sentence with?

**Comment by kbenne** [comment]
@Myoldmopar 1.8.1

**Comment by kbenne** [comment]
@mbadams5 I'm actually working now to get this merged into my hpwh branch, resolve conflicts, test and reintegrate

**Pull request merged**
