### PR TITLE
Bundle

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@kbenne can you review this?  i'd suggest merging this iteration but wanted to run it by you first.

**Comment by kbenne** [comment]
yeah. i guess i missed my chance.

**Comment by kbenne** [comment]
I did just glance through it. I believe you uploaded new ruby binaries for windows, right?

**Comment by macumber** [comment]
No new ruby binaries, I thought I might have to rebuild to reimplement autoload, but I came up with my hack.  I just fixed some of the build rules for the future.  I did update gems in the openstudio gem list though

**Pull request merged**
