### PR TITLE
Standardize return types

### PR DESCRIPTION
**Pull request by jmarrec**
Trying to address a few things that were annoying me:

* Stripped all trailing whitespaces in all files except ./dependencies. (My editor is configured to strip those when saving a file (which should be the norm for everyone), and whitespace stuff keeps poping up in pretty much all of my changes as a result...)

* Addressed #2620 to make all setXXX methods return a bool.

2417 methods were initially `void` instead of `bool` ("grep "void set" *.hpp, includes both the public and the impl ones). Now there are none left.

There are still methods that should probably be bool but they aren't called setXXX.

### CODE REVIEW

**Comment by jmarrec** [comment]
Merge conflicts are just whitespace conflicts... Which I've tried to resolve, but don't have write access.

**Comment by macumber** [comment]
Let's wait on this one until after code freeze

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by macumber** [comment]
Leftover methods not handled:

`ExternalInterfaceFunctionalMockupUnitImportFromVariable_Impl.hpp:
void setOutputVariableIndexKeyName(const std::string& outputVariableIndexKeyName);
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);


ExternalInterfaceFunctionalMockupUnitExportToVariable.hpp:
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitImportToActuator.hpp:
void setActuatedComponentType(const std::string& actuatedComponentType);
void setActuatedComponentControlType(const std::string& actuatedComponentControlType);
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitImport_Impl.hpp:
void setFMUTimeout(double fMUTimeout);
void setFMULoggingOn(int fMULoggingOn);


ExternalInterfaceFunctionalMockupUnitExportToActuator.hpp:
void setActuatedComponentType(const std::string& actuatedComponentType);
void setActuatedComponentControlType(const std::string& actuatedComponentControlType);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitImportToVariable.hpp:
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceSchedule_Impl.hpp:
void setInitialValue(double initialValue);
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceSchedule.hpp:
void setInitialValue(double initialValue);
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceFunctionalMockupUnitImport.hpp:
void setFMUTimeout(double fMUTimeout);
void setFMULoggingOn(int fMULoggingOn);


ExternalInterfaceFunctionalMockupUnitExportToVariable_Impl.hpp:
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitImportToVariable_Impl.hpp:
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitImportToSchedule_Impl.hpp:
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceActuator_Impl.hpp:
void setOptionalInitialValue(double optionalInitialValue);
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceActuator.hpp:
void setOptionalInitialValue(double optionalInitialValue);
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceVariable.hpp:
void setInitialValue(double initialValue);
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceFunctionalMockupUnitExportToActuator_Impl.hpp:
void setActuatedComponentType(const std::string& actuatedComponentType);
void setActuatedComponentControlType(const std::string& actuatedComponentControlType);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitImportToSchedule.hpp:
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitExportToSchedule.hpp:
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


EnergyManagementSystemOutputVariable.hpp:
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceFunctionalMockupUnitExportFromVariable_Impl.hpp:
void setOutputVariableIndexKeyName(const std::string& outputVariableIndexKeyName);
void setFMUVariableName(const std::string& fMUVariableName);


ExternalInterfaceFunctionalMockupUnitExportFromVariable.hpp:
void setOutputVariableIndexKeyName(const std::string& outputVariableIndexKeyName);
void setFMUVariableName(const std::string& fMUVariableName);


OutputVariable_Impl.hpp:
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceFunctionalMockupUnitImportFromVariable.hpp:
void setOutputVariableIndexKeyName(const std::string& outputVariableIndexKeyName);
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);


ExternalInterfaceVariable_Impl.hpp:
void setInitialValue(double initialValue);
void setExportToBCVTB(bool exportToBCVTB);


ExternalInterfaceFunctionalMockupUnitImportToActuator_Impl.hpp:
void setActuatedComponentType(const std::string& actuatedComponentType);
void setActuatedComponentControlType(const std::string& actuatedComponentControlType);
void setFMUInstanceName(const std::string& fMUInstanceName);
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


ExternalInterfaceFunctionalMockupUnitExportToSchedule_Impl.hpp:
void setFMUVariableName(const std::string& fMUVariableName);
void setInitialValue(double initialValue);


OutputVariable.hpp:
void setExportToBCVTB(bool exportToBCVTB);


EnergyManagementSystemOutputVariable_Impl.hpp:
void setExportToBCVTB(bool exportToBCVTB);`

**Comment by jmarrec** [comment]
I just handled all of these @macumber (very little QA/QC done though).

Make sure you run all tests :)

**Comment by jmarrec** [comment]
@macumber regarding the fact that in many places I replaced:

    bool result = setXXX...
    OS_ASSERT(result);

with:

    bool result = setXXX...
    return result;

Since you told me you've have kept them (they are compiled out when building Release, but may be helpful in Debug mode), I just readded them.

I realized during the night that one way to re-add the OS_ASSERT back was to use git diff.

so I did a git diff between the HEAD of my branch and the SHA on develop where I branched off and exported that into a text file.

    git diff 553516614161dda1c9117f671e9584e24675bf28..HEAD > patch.diff

I then used python (with [unidiff](https://github.com/matiasb/python-unidiff)) to find in each `model/*.cpp` file where I replaced `OS_ASSERT(result);` with `return result;`, I got all lines numbers. 

Then I wrote a little something to open the file, insert the "OS_ASSERT(result)" line back in the right place, and save.

**Comment by jmarrec** [comment]
Fixed a failing model Surface_GTest.cpp -> Surface_IddAssumptions introduced in #2902 here: https://github.com/NREL/OpenStudio/pull/2902/files#diff-20dc466cd26aed8488ee9b0bb0d5ce9a

A new outside boundary condition - 'Foundation'- was added but the Gtest wasn't updated.

**Pull request closed without merging**
