### PR TITLE
adding OS:UnitarySystemPerformance:Multispeed

### PR DESCRIPTION
**Pull request by nmerket**

### CODE REVIEW

**Comment by macumber** [comment]
@nmerket is this pull request just to add the idd object?  it is not wrapped or translated?

**Comment by nmerket** [comment]
I just pushed some of my local commits. It's not done yet. I still need to write regression tests for the forward translation like we discussed.

**Comment by nmerket** [comment]
@macumber @kbenne @shorowit This is ready to go.

**Comment by nrel-bot-3** [comment]
@nmerket @lgentile it has been 7 days since this pull request was last updated.

**Comment by nmerket** [comment]
I just learned something in #2636 that means I need to fix some things for SWIG here. Don't merge yet.

**Comment by nmerket** [comment]
And we're good to go again.

**Pull request merged**
