### PR TITLE
Fix #2812

### LINKED ISSUE #2812: Incorrect MultiSpeed forward translation in 2.3 pre-release
I'm using the 2.3 pre-release on GitHub. This appears to be a regression relative to 2.2.

This OSM has a `OS:Coil:Cooling:DX:MultiSpeed` object with 4 `StageData` objects.
[in.osm.txt](https://github.com/NREL/OpenStudio/files/1356388/in.osm.txt)

The resulting IDF has a `Coil:Cooling:DX:MultiSpeed` with 4 speeds, but only 3 speeds worth of fields written. 
[in.idf.txt](https://github.com/NREL/OpenStudio/files/1356394/in.idf.txt)

This causes failed E+ simulations with errors like:
```
** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="RESIDENTIAL CENTRAL AC COOLING COIL", missing
   **   ~~~   ** ...required Speed 4 Total Cooling Capacity Function of Temperature Curve Name is blank.
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="RESIDENTIAL CENTRAL AC COOLING COIL", missing
   **   ~~~   ** ...required Speed 4 Total Cooling Capacity Function of Flow Fraction Curve Name is blank.
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="RESIDENTIAL CENTRAL AC COOLING COIL", missing
   **   ~~~   ** ...required Speed 4 Energy Input Ratio Function of Temperature Curve Name is blank.
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="RESIDENTIAL CENTRAL AC COOLING COIL", missing
   **   ~~~   ** ...required Speed 4 Energy Input Ratio Function of Flow Fraction Curve Name is blank.
   ** Severe  ** GetDXCoils: Coil:Cooling:DX:MultiSpeed="RESIDENTIAL CENTRAL AC COOLING COIL", missing
   **   ~~~   ** ...required Speed 4 Part Load Fraction Correlation Curve Name is blank.
```

cc @joseph-robertson

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #2812.

Used lldb to debug. In the ForwardTranslator, it does loop on the 4th stage, but the idfObject stays at size [74], it's a problem of `\max-fields` in `ProposedEnergy+.idd`.

I wrote a new Forward Translator Gtest for this to avoid running into the same problem, it's currently building so I expect a few typos, but the solution is found anyways.

Perhaps the other objects that have `\max-fields` should be double checked too in the `ProposedEnergy+.idd`.

Review assignee: @kbenne (original assignee in #2812)

### CODE REVIEW

**Comment by jmarrec** [comment]
This works now.

Side note @kbenne: I did notice that you can add the `CoilCoolingDXMultiSpeed` directly on an `AirLoopHVAC`, which is bound to produce an E+ crash, since according to the [I/O](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-heating-and-cooling-coils.html#coilcoolingdxmultispeed) it **must** be wrapped into an `AirLoopHVAC:UnitarySystem:xx` object. Perhaps the `addToNode` method should be overwritten to restrict.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
