### PR TITLE
 Improve addViewFactor performance, second try

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #3713.

### CODE REVIEW

**Comment by shorowit** [comment]
2.9-rc3:
```
49 view factors => 0.02 sec
64 view factors => 0.03 sec
81 view factors => 0.04 sec
100 view factors => 0.07 sec
121 view factors => 0.1 sec
144 view factors => 0.14 sec
169 view factors => 0.22 sec
196 view factors => 0.29 sec
225 view factors => 0.44 sec
256 view factors => 0.61 sec
289 view factors => 0.83 sec
324 view factors => 1.14 sec
361 view factors => 1.51 sec
400 view factors => 1.99 sec
441 view factors => 2.65 sec
484 view factors => 3.38 sec
529 view factors => 4.5 sec
576 view factors => 5.66 sec
625 view factors => 7.32 sec
676 view factors => 9.2 sec
```

this branch:
```
49 view factors => 0.01 sec
64 view factors => 0.03 sec
81 view factors => 0.03 sec
100 view factors => 0.06 sec
121 view factors => 0.07 sec
144 view factors => 0.11 sec
169 view factors => 0.14 sec
196 view factors => 0.23 sec
225 view factors => 0.3 sec
256 view factors => 0.44 sec
289 view factors => 0.61 sec
324 view factors => 0.76 sec
361 view factors => 0.97 sec
400 view factors => 1.38 sec
441 view factors => 1.87 sec
484 view factors => 2.44 sec
529 view factors => 2.94 sec
576 view factors => 3.94 sec
625 view factors => 5.1 sec
676 view factors => 5.92 sec
```

**Comment by jmarrec** [comment]
@joseph-robertson I would add a method that doesn't perform checks like whether to/from Surface are part of thermal zones nor check for an existing view Factor;

```
  bool ZonePropertyUserViewFactorsBySurfaceName_Impl::addViewFactorNoChecks(const ViewFactor& viewFactor) {

    // If existing, get it, otherwise Push an extensible group. ModelExtensibleGroup cannot be default-constructed, so use a ternary operator
    std::vector<std::string> temp;
    ModelExtensibleGroup eg = pushExtensibleGroup(temp, false).cast<ModelExtensibleGroup>();

    bool from = eg.setPointer(OS_ZoneProperty_UserViewFactors_BySurfaceNameExtensibleFields::FromSurfaceName, viewFactor.fromSurface().handle());
    if (!from) {
      LOG(Error, "Unable to add View Factor which has an incompatible fromSurface object to " << briefDescription());
      OS_ASSERT(false);
    }

    bool to = eg.setPointer(OS_ZoneProperty_UserViewFactors_BySurfaceNameExtensibleFields::ToSurfaceName, viewFactor.toSurface().handle());
    if (!to) {
      LOG(Error, "Unable to add View Factor which has an incompatible toSurface object to " << briefDescription());
      OS_ASSERT(false);
    }

    bool value = eg.setDouble(OS_ZoneProperty_UserViewFactors_BySurfaceNameExtensibleFields::ViewFactor, viewFactor.viewFactor());
    if (from && to && value) {
      result = true;
    } else {
      // Something went wrong
      // So erase the new extensible group
      getObject<ModelObject>().eraseExtensibleGroup(eg.groupIndex());
      result = false;
    }
    return result;

  }
```

Could even push it to

```
  bool ZonePropertyUserViewFactorsBySurfaceName_Impl::addViewFactorNoChecks(const ViewFactor& viewFactor) {

    std::vector<std::string> temp({toString(viewFactor.fromSurface().handle()), toString(viewFactor.toSurface().handle()), toString(viewFactor.viewFactor()});

    pushExtensibleGroup(temp, false);

    return true;

  }
```

**Comment by jmarrec** [comment]
vf_me_1: `zone_prop.addViewFactor(os_vf, true)`
vf_me_2_false:  `zone_prop.addViewFactor(os_vf, false)`
vf_me_3_unsafe: `zone_prop.addViewFactorUnsafe(os_vf)`

image

**Comment by mbadams5** [comment]
@jmarrec You should really performance timings using Release or at least RelWithDebInfo. It is not a fair comparison since Release will add performance optimizations that may change the timings. I have seen it before where something had a big performance improvement in a Debug build but then had no change in a Release build since the compiler optimized it properly.
That said, your timings may still be valid and have a similar trend in a Release build.

**Comment by jmarrec** [comment]
@mbadams5 yep I know, I just built debug since that's what I had ready on hands. I did build release after posting this and saw similar factors.

**Pull request closed without merging**
