### PR TITLE
Fix for containingHVACComponent

### LINKED ISSUE #4781: CoilHeatingDXMultiSpeed .containingHVACComponent
Issue overview
--------------
The AirLoopHVACUnitarySystem object can accept a CoilHeatingDXMultiSpeed object, but the .containingHVACComponent method does not return the AirLoopHVACUnitarySystem for CoilHeatingDXMultiSpeed objects

## Current Behavior
.containingHVACComponent returns nil

## Expected Behavior
.containingHVACComponent returns the AirLoopHVACUnitarySystem object

## Steps to Reproduce
Example model on NREL's sharepoint: 
https://nrel.sharepoint.com/:u:/s/NRELBuildings/EZ9GOFR2Wy9NhVomACRrwUYBGrPwjs8h2p-7-hAmZkcZ9A?e=4M3KIo
_(let me know if I should upload it elsewhere)_
```
require 'openstudio'

osm_path = File.dirname(__FILE__) + '/multispeed_hps.osm'
translator = OpenStudio::OSVersion::VersionTranslator.new
model = translator.loadModel(osm_path).get

model.getAirLoopHVACUnitarySystems.each do |sys|
  puts sys
end

puts "################################################3"

model.getCoilHeatingDXMultiSpeeds.each do |coil|
  puts coil
  airloop = coil.airLoopHVAC.is_initialized
  hvac_comp = coil.containingHVACComponent.is_initialized
  zone_hvac_comp = coil.containingZoneHVACComponent.is_initialized
  puts ''
  puts "airloop? #{airloop}"
  puts "hvac_comp? #{hvac_comp}"
  puts "zone_hvac_comp? #{zone_hvac_comp}"
end
```

## Possible Solution
Support the .containingHVACComponent method for CoilHeatingDXMultiSpeed objects. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): OS 3.4

### [Context](url)
I'm trying to access the supplemental coil on the paired AirLoopHVACUnitarySystem object for CoilHeatingDXMultiSpeed object.  This is for the ComStock EUSS project.  It is not time sensitive; I've already implemented and tested a workaround by looping through AirLoopHVACUnitarySystem objects and matching the heating coil.

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4781

Update `containingHVACComponent` method.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
Have you tried modifying one of the Resources test to ensure that it runs through E+?

**Comment by joseph-robertson** [comment]
I have not. Is it required that a test be modified? We can't just run it through all the tests?

**Comment by tijcolem** [comment]
Note to run regressions tests on installers https://github.com/NREL/OpenStudio-resources

**Comment by jmarrec** [comment]
> I have not. Is it required that a test be modified? We can't just run it through all the tests?

I'm not necesarilly suggesting to make a PR with a new test and all that stuff.

Quickly modify one test and make sure it runs.

**Review by jmarrec — APPROVED** [review]

**Pull request merged**
