### PR TITLE
Fuel query updates

### LINKED ISSUE #4705: Review SqlFile wrapped queries for 'Additional Fuel'
Issue overview
--------------
The SqlFile wrapped queries need some review. For example : https://github.com/NREL/OpenStudio/blob/6640698cfbf0d5fee1461f80fd343b396a226321/src/utilities/sql/SqlFile_Impl.cpp#L1561-L1565
Although the wrapped queries are still in use (for example in the Xcel reporting measure) I don't think ColumnName ='Additional Fuel' exists anymore and the queries are all returning 0.

### PR DESCRIPTION
**Pull request by kflemin**
Pull request overview
---------------------

 - Fixes #4705 

Added SqlFile methods for end uses for all fuel types: gasoline, diesel, propane, coal, fuel oil No 1, fuel oil No 2, other fuel 1, and other fuel 2.  Deprecating "other_fuel" queries as they used to pull something called "Additional Fuel" from the database and that quantity no longer exists

Also added tests to ensure each of these fuels can be retrieved.

### CODE REVIEW

**Comment by tijcolem** [comment]
@kflemin Do you know if any these deprecated methods have replacement methods? I think rather than marking deprecated and logging we should remove the methods as the current behavior returns zero result values when they query the db vs throwing an error.  Thoughts? 

```
OS_DEPRECATED boost::optional<double> otherFuelHeating() const;

    /// Returns the energy used for cooling from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelCooling() const;

    /// Returns the energy used for interior lighting from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelInteriorLighting() const;

    /// Returns the energy used for exterior lighting from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelExteriorLighting() const;

    /// Returns the energy used for interior equipment from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelInteriorEquipment() const;

    /// Returns the energy used for exterior equipment from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelExteriorEquipment() const;

    /// Returns the energy used for fans from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelFans() const;

    /// Returns the energy used for pumps from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelPumps() const;

    /// Returns the energy used for heat rejection from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelHeatRejection() const;

    /// Returns the energy used for humidification from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelHumidification() const;

    /// Returns the energy used for heat recovery from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelHeatRecovery() const;

    /// Returns the energy used for water systems from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelWaterSystems() const;

    /// Returns the energy used for refrigeration from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelRefrigeration() const;

    /// Returns the energy used for generators from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelGenerators() const;

    /// Returns the energy used for all end uses from other fuel in gigajoules.
    /// Requires EnergyPlus simulation output to calculate.
    OS_DEPRECATED boost::optional<double> otherFuelTotalEndUses() const;
```

**Comment by kflemin** [comment]
@tijcolem, otherFuel is now Other Fuel 1 and Other Fuel 2. It's true that the current behavior returns 0s and that's misleading.  I'm fine with whatever you think is best!

**Comment by tijcolem** [comment]
@kflemin I would say If there isn't a direct replacement for a deprecated method (e.g. otherFuelPumps -> otherFuelPumps1 ) then we should remove the old method. If we can safely have the  deprecated methods call the new method and LOG to info the user that this method is deprecated, this would be preferred.

**Comment by kflemin** [comment]
@tijcolem, I removed the deprecated methods...this should be good to go!

**Pull request merged**
