### PR TITLE
Addresses #3578, warning message when running measure test 'Cannot find current Workflow Step'

### LINKED ISSUE #3578: Warning message when running measure test 'Cannot find current Workflow Step'
This error is logged in the following places:
* https://github.com/NREL/OpenStudio/blob/develop/src/measure/OSRunner.cpp#L196-L200
* https://github.com/NREL/OpenStudio/blob/develop/src/measure/OSRunner.cpp#L271-L275

It occurs when initializing `runner = OpenStudio::Measure::OSRunner.new(OpenStudio::WorkflowJSON.new)`
and then calling `measure.run(model, runner, argument_map)`.

Results in warning 'Cannot find current Workflow Step'

The previous lines come with the template unit test files for new measures.

Seems like we could remove the warnings from OSRunner.cpp altogether, but here are some notes from @macumber :
```
id rather give the runner an extra flag like 'testingMode = true' than completely remove that check
then we could raise the warning to an error and not give the issue in testing mode
although measures using the runner would not be able to get the current step
so maybe a better method is one that automatically creates a workflow with the current measure
```

@shorowit

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #3578

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
@joseph-robertson Did you test running measures and measures' test with this change?

**Comment by joseph-robertson** [comment]
Yes, I did.

**Comment by jmarrec** [comment]
Locally built 1e4131ce0ae2de1ea9d7cc4ee99da0841e5f556e on Ubuntu, still seeing the message.

```
(py38)julien@~$ pry
You are running ruby 2.5.5p157: OpenStudio develop3
Do you want OpenStudio (os) or os-debug (1) / os-release (2), or os-app-debug (3) / os-app-release (4): [os/1/2/3/4] 2
Loading '/home/julien/Software/Others/OS-build-release/Products/ruby/openstudio': 3.0.1-beta+1e4131ce0a

require '/home/julien/Software/Others/openstudio_gems/OpenStudio-measures/nrel_published/openstudio_results/measure.rb'
measure = OpenStudioResults.new
runner = OpenStudio::Measure::OSRunner.new(OpenStudio::WorkflowJSON.new)
arguments = measure.arguments
argument_map = OpenStudio::Measure.convertOSArgumentVectorToMap(arguments)
measure.run(runner, argument_map)
[openstudio.measure.OSRunner] <-1> Cannot find current Workflow Step
=> false
```

**Comment by joseph-robertson** [comment]
My motivation for changing it to an `Info` was that it was returning, but not returning false. I'm not sure what the advantage is of reporting an `Error` and then not returning false?

**Pull request merged**
