### PR TITLE
1973 add dual duct terminals

### PR DESCRIPTION
**Pull request by kbenne**

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by macumber** [comment]
@kbenne should this make it into 1.14?

**Comment by nrel-bot-2** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by jmarrec** [comment]
@kbenne please close this one as I have expanded upon it on #2877

**Pull request merged**
