### PR TITLE
Finish removing "additional_ruby_libs"

### PR DESCRIPTION
**Pull request by lefticus**
Relies on conan-openstudio-ruby package that contains the FFI that it
had to build.

The solution is to make sure that the ruby package provides all of the
necessary dependencies.

### CODE REVIEW

**Comment by jmarrec** [comment]
Grrrrr CI can't build it to E+ version mismatch. Would need to merge #3725 before CI can run this one.. (or any develop3 PRs for that matter)

**Comment by jmarrec** [comment]
@lefticus There are some new failing tests with this PR versus develop3 (#3725):

```
['CLITest-test_embedded_help-file_read',
 'CLITest-test_embedded_help-fileutils_mv',
 'CLITest-test_embedded_ruby-json',
 'CLITest-test_encodings-encoding',
 'CLITest-test_encodings-encoding2']
```

---------------

All failing tests for reference:
```
The following tests FAILED:
	 50 - RubyTest-PathWatcher_Test-watchFile (Failed)
	 51 - RubyTest-PathWatcher_Test-watchDir (Failed)
	 93 - RubyTest-WorkspaceWatcher_Test-WorkspaceWatcher (Failed)
	640 - BCLFixture.BCLMeasure (Failed)
	1945 - ModelFixture.Space_intersectSurfaces_degenerate1 (Failed)
	1946 - ModelFixture.Space_intersectSurfaces_degenerate2 (Failed)
	1947 - ModelFixture.Space_intersectSurfaces_degenerate3 (Failed)
	2069 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper (Failed)
	2161 - EnergyPlusFixture.ErrorFile_WarningsAndSevere (Failed)
	2162 - EnergyPlusFixture.ErrorFile_WarningsAndCrash (Failed)
	2572 - CLITest-PathWatcher_Test-watchFile (Failed)
	2573 - CLITest-PathWatcher_Test-watchDir (Failed)
	2615 - CLITest-WorkspaceWatcher_Test-WorkspaceWatcher (Failed)
	2617 - CLITest-test_bundle-bundle (Failed)
	2618 - CLITest-test_bundle-bundle_git (Failed)
	2624 - CLITest-test_embedded_help-file_read (Failed)
	2625 - CLITest-test_embedded_help-fileutils_mv (Failed)
	2637 - CLITest-test_embedded_ruby-json (Failed)
	2654 - CLITest-test_encodings-encoding (Failed)
	2655 - CLITest-test_encodings-encoding2 (Failed)
````

**Comment by lefticus** [comment]
I think we may have some transient errors - I showed only 15 failures when I last ran the tests, and it was consistent between my patches and develop3.

**Comment by lefticus** [comment]
@jmarrec I cannot even configure a clean build of develop3 now - it complains about missing SWIG with a "this shouldn't happen" error.

**Comment by jmarrec** [comment]
@lefticus Is that on windows? Is that with 8518aec953487da27b30cc1e7efcbc5d19e5b7ff (post conan SWIG 4.0)?

**Comment by jmarrec** [comment]
@lefticus I'm going to merge this, I don't see why it would be responsible for the failure of the tests, and we do need to get all tests passing, so we can address later.

**Pull request merged**
