### PR TITLE
Fix #3604 - Allow AirConditioner:VariableRefrigerant condenser Type=WaterCooled (and EvaporativelyCooled)

### LINKED ISSUE #3604: As a user, I want to be able to connect the AirConditionerVariableRefrigerantFlow to a plant loop so that I can model WC-VRF units
Currently OpenStudio doesn't support water-cooled VRF units as seen in the code here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/AirConditionerVariableRefrigerantFlow.cpp#L1925

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #3604 - Allow AirConditioner:VariableRefrigerant condenser Type=WaterCooled (and EvaporativelyCooled)

### CODE REVIEW

**Comment by jmarrec** [comment]
@kbenne 

I just noticed something in `ZoneHVAC:TerminalUnit:VariableRefrigerantFlow`

```
OpenStudio:   N10; \field Rated Total Heating Capacity Sizing Ratio
EnergyPlus:    N10, \field Rated Heating Capacity Sizing Ratio
```

Similarly in `Coil:Cooling:DX:VariableRefrigerantFlow`:
```
OpenStudio:   N1 , \field Rated Total Cooling Capacity
EnergyPlus:    N1 , \field Gross Rated Total Cooling Capacity
```

I'm not sure it was a great idea to start matching up E+ and OpenStudio.idd.

3 options:
1) Undo the change I've done to AirConditionerVariableRefrigerantFlow (keep old IDD name and methods)
2) Do make the change in other objects that are VRF related
3) Keep changes only to AirConditionerVariableRefrigerantFlow. 3.1) Keep `OS_DEPRECRATED` on old methods   3.2) Remove `OS_DEPRECATED`

**Comment by macumber** [comment]
@jmarrec Is this branch ready for 2.9.0 or is there more discussion needed?

**Comment by macumber** [comment]
@jmarrec is this the corresponding test in resources?  https://github.com/NREL/OpenStudio-resources/pull/75

**Comment by jmarrec** [comment]
@macumber, this is the linked test yes.

Discussion was still on going until last friday but @kbenne gave the final word in https://github.com/NREL/OpenStudio/issues/3604#issuecomment-526737137 which happens to be a different design decisiom than the one I made so I need to redo this one and the linked test. Will try to get it done this week

**Comment by jmarrec** [comment]
@macumber Ready for review (IIUC @kbenne isn't available)

**Comment by jmarrec** [comment]
I changed the base to the everybody_merge_now, but CI won't build that, so I'll change that back to develop.

**Comment by jmarrec** [comment]
Mac CI built this correctly. Killed the rest.

**Pull request merged**
