### PR TITLE
2091 wrapped hpwh

### PR DESCRIPTION
**Pull request by kbenne**

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by Myoldmopar** [comment]
@kbenne Curious, where does this fall in line of priority?  Complete bottom, or just somewhere near the bottom?  And is there anything I can do to help?  Is it ready to be reviewed or still needs development work?

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @lgentile it has been 7 days since this pull request was last updated.

**Comment by nmerket** [comment]
#2091

**Comment by kbenne** [comment]
Yep. I'm going to have a little party now that this is finally out of my pivotal queue.

**Comment by nmerket** [comment]
Me too!

**Pull request merged**
