### PR TITLE
90664130 alternative model pat

### PR DESCRIPTION
**Pull request by macumber**
@asparke2 I still want to fix a few bugs in PAT but this new feature is ready for initial testing

### CODE REVIEW

**Comment by macumber** [comment]
@asparke2 are you able to build and test?

**Comment by asparke2** [comment]
@macumber Yes, I will test

**Comment by asparke2** [comment]
@macumber After merging develop into this branch, it works all the way through with the Xcel Measures.  I also tested importing an existing file with external measures, and that also works. There is one crash (not convinced it is related to your changes), and one change request.

Crash:
If you open a PAT project from a previous version, then try to save it after the upgrades, PAT crashes.  However, after the crash, if you re-open PAT and re-open the same project, it works fine (no crash on save).  I have a PAT file you can use to reproduce if you want.

crash message

Change request:
If a user creates a design alternative from external file and has 0 user-defined measures, the XML will leave out the /measures element.  The XML is still valid, but EDAPT will choke on it.  If there are 0 measures, can we add that to the warning dialog message and not export that design alternative to the XML?  Otherwise I will get questions about why isn't EDAPT working with this file.  You can imagine how I already know that this particular thing breaks EDAPT :)

**Comment by macumber** [comment]
Thanks @asparke2 I'll look into the crash and can add that warning

**Comment by macumber** [comment]
@asparke2 this is ready for you to review again.  Can you also look at the two issues that are still unchecked on the pivotal ticket?  I believe those can be closed in github.  Finally, are you able to write some documentation for this new feature to include in the PAT reference guide?

**Comment by macumber** [comment]
Closes  #1388

**Comment by asparke2** [comment]
@macumber This looks good, the change request to not export the extra thing and the file opening crash appear to be fixed.  I was able to reproduce the other two bugs you mentioned on the pivotal ticket, but I don't think those should hold up this work unless you think they are easy fixes.

**Pull request merged**
