### PR TITLE
Unset ruby envs in openstudio_cli.rb

### LINKED ISSUE #4067: OpenStudio CLI and ruby envs
## Current Behavior

When using the openstudio cli with ruby managers such as rvm, envs that are set by rvm in the current shell can be read by the CLI and cause errors. 

## Expected Behavior
The CLI should not read these values.  

## Steps to Reproduce
For instance, running the following test using the CLI produces the following. 

```
rvm use 2.5.5 
Using /Users/tijcolem/.rvm/gems/ruby-2.5.5
ruby -v 
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
openstudio model_tests.rb -n test_plenums_rb
Error executing argv: ["-n", "test_plenums_rb"]
Error: cannot load such file -- minitest/autorun in eval:121:in `require'
eval:121:in `require'
:/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
:/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/tijcolem/git/OpenStudio-resources/test_helpers.rb:12:in `<top (required)>'
eval:121:in `require'
eval:121:in `require'
:/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
eval:190:in `require_relative'
/Users/tijcolem/git/OpenStudio-resources/model_tests.rb:4:in `<top (required)>'
eval:121:in `require'
eval:121:in `require'
:/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
:/openstudio_cli.rb:1507:in `execute'
:/openstudio_cli.rb:750:in `execute'
:/openstudio_cli.rb:1744:in `<main>'
eval:174:in `eval'
eval:174:in `require_embedded_absolute'
eval:160:in `block in require_embedded'
eval:154:in `each'
eval:154:in `require_embedded'
eval:113:in `require'
eval:3:in `<main>'
```
Does not fail when using the system ruby as envs get unset. 
 ```
rvm use system 
Now using system ruby.
ruby -v 
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
openstudio model_tests.rb -n test_plenums_rb

# Running tests with run options :

Running for OpenStudio 3.0.1+09b7c8a554
Running for OpenStudio 3.0.1+09b7c8a554 (Previous=3.0.0)

# Running tests with run options -n test_plenums_rb --seed 22470:

Finished tests in 57.322032s, 0.0174 tests/s, 0.0349 assertions/s.

1 tests, 2 assertions, 0 failures, 0 errors, 0 skips

```

If you unset GEM_HOME and GEM_PATH after invoking `rvm use 2.5.5` it also works. 

```
rvm use 2.5.5 
Using /Users/tijcolem/.rvm/gems/ruby-2.5.5
ruby -v 
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
env | grep GEM
GEM_HOME=/Users/tijcolem/.rvm/gems/ruby-2.5.5
GEM_PATH=/Users/tijcolem/.rvm/gems/ruby-2.5.5:/Users/tijcolem/.rvm/gems/ruby-2.5.5@global
unset GEM_HOME
unset GEM_PATH
openstudio model_tests.rb -n test_plenums_rb

# Running tests with run options :

Running for OpenStudio 3.0.1+09b7c8a554
Running for OpenStudio 3.0.1+09b7c8a554 (Previous=3.0.0)

# Running tests with run options -n test_plenums_rb --seed 49232:
Finished tests in 57.325366s, 0.0174 tests/s, 0.0349 assertions/s.
1 tests, 2 assertions, 0 failures, 0 errors, 0 skips
```

## Possible Solution
Unset all ruby related ENVs in CLI. 

### Environment

OSX 10.14 
OpenStudio Version: 3.0.1+09b7c8a554

### PR DESCRIPTION
**Pull request by tijcolem**
- Fixes #4067 

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by macumber** [comment]
This is related to https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/runner.rb#L183

Be careful here because there are a lot of possible use cases here (e.g calling the CLI to do standards sizing run in workflow using a bundle, etc)

**Comment by tijcolem** [comment]
Thanks for the heads up @macumber.   My understanding with the recent changes of how bundler works as of version > 3.0.1, openstudio_cli.rb should only explicitly set these ruby envs based on arguments to the CLI (e.g. --gem_home). It should never use the parent process envs by doing something like: 

```
export GEM_HOME = /some/path/to/gem_home
export GEM_PATH = /some/path/to/gem_home
# run CLI
openstudio some_command
```

As far as openstudio-gems, I looked into these and did a simple `grep -r GEM_HOME ./openstudio-gems/` to see what might be using them. Besides bundler, these gems make use of them but they also unset them on the init/setup functions. 

https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/runner.rb#L183-L204

https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards.rb#L416-L427

The only other thing I can think of is ruby bindings but that gets set up by the wrapper - https://github.com/NREL/OpenStudio/blob/develop/ruby/openstudio.rb  and we are not modifying those envs there. 

I think these changes are what we want and just unset these to prevent unwanted usage in the CLI unless you know of a use case that might cause issues? I can't think of any of looking through things.

**Comment by macumber** [comment]
Are these still accepted as command line arguments? 

https://github.com/NREL/OpenStudio/blob/develop/src/cli/openstudio_cli.rb#L387

**Comment by macumber** [comment]
The biggest use case to me was to be able to use different versions of the OpenStudio Standards Gem.  URBANopt was built around the idea that each project would have a Gemfile that pulls in all the URBANopt gems you want for your project.

**Comment by tijcolem** [comment]
Yep, those are all still excepted args to the cli so no changes there.  So you can still do this if you wanted to use a custom openstudio-standards gem. 

1 ) Create simple Gemfile for custom openstudio-standards 

```
cat <<EOF >> Gemfile
source 'http://rubygems.org'
ruby "~> 2.5.0"
gem 'openstudio-standards', '= 0.2.12.rc2'
EOF
```
2 ) Install gems via bundler 
`bundle install --path custom-standards-gems`

3 ) Run cli with custom gems 
`openstudio --bundle Gemfile --bundle_path custom-standard-gems somefile.rb`

Note that the above workflow is unique to OpenStudio versions > 3.0.1 as you now only need to install the gems you want to use with OpenStudio vs all gems. 

I don't think we want this anymore: https://github.com/NREL/OpenStudio/blob/develop/src/cli/openstudio_cli.rb#L416-L418  Thanks for pointing it out.  The idea here is to drive the CLI with args only and not accept ruby envs from the shell since many users have rvm which sets these automatically and causes unwanted behavior in the CLI.

**Comment by macumber** [comment]
Sounds good Tim!

**Comment by jmarrec** [comment]
Building develop, without this fix:

```
(py38)julien@OS-build-release$ gem list | grep minitest
(py38)julien@OS-build-release$ ctest -j 16 -R Calendar_Test-daylight_saving
Test project /home/julien/Software/Others/OS-build-release
    Start 2825: RubyTest-Calendar_Test-daylight_savings
    Start 2917: CLITest-Calendar_Test-daylight_savings
1/2 Test #2825: RubyTest-Calendar_Test-daylight_savings ...***Failed    0.31 sec
gem install minitest2/2 Test #2917: CLITest-Calendar_Test-daylight_savings ....   Passed    5.19 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   8.00 sec

The following tests FAILED:
	2825 - RubyTest-Calendar_Test-daylight_savings (Failed)
Errors while running CTest
(py38)julien@OS-build-release$ gem install minitest
Fetching: minitest-5.14.2.gem (100%)
Successfully installed minitest-5.14.2
1 gem installed
(py38)julien@OS-build-release$ ctest -j 16 -R Calendar_Test-daylight_saving
Test project /home/julien/Software/Others/OS-build-release
    Start 2825: RubyTest-Calendar_Test-daylight_savings
    Start 2917: CLITest-Calendar_Test-daylight_savings
1/2 Test #2825: RubyTest-Calendar_Test-daylight_savings ...   Passed    0.34 sec
2/2 Test #2917: CLITest-Calendar_Test-daylight_savings ....***Failed    0.48 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   3.29 sec

The following tests FAILED:
	2917 - CLITest-Calendar_Test-daylight_savings (Failed)
Errors while running CTest
```

**Review by jmarrec — APPROVED** [review]
Tested that everything works fine for me and that it does fix the problem

**Pull request merged**
