### PR TITLE
Update to v9.4.0-IOFreeze

### LINKED ISSUE #4042: Update to EnergyPlus 9.4.0
Enhancement Request
--------------

v9.4.0-IOFreeze is released, so we should update to it.

## Detailed Description

https://github.com/NREL/EnergyPlus/blob/v9.4.0-IOFreeze-RC1/src/Transition/InputRulesFiles/Rules9-3-0-to-9-4-0.md

### Major changes

- [ ] Allow multiple shading controls for a subsurface https://github.com/NREL/EnergyPlus/pull/8196
- [x] Update WaterHeater:Stratified FT to avoid warning https://github.com/NREL/EnergyPlus/pull/8172
    - Note JM: There should be nothing needed here, but we should test to ensure this is the case.
    - Merge of https://github.com/NREL/EnergyPlus/pull/8172 happened post v9.4.0-IOFreeze, so need to wait for another package to make sure. Resources test `coil_waterheating_desuperheater.rb` will serve as an example, see if that removes the `   ** Warning ** WaterHeater:Stratified = 100GAL NATURAL GAS WATER HEATER - 2883KBTU/HR:  More Additional Loss Coefficients were entered than the number of nodes; extra coefficients will not be used` warning.
- [x] ZoneHVAC:LowTemperatureRadiant:Electric
- [x] ZoneHVAC:LowTemperatureRadiant:ConstantFlow
- [x] ZoneHVAC:LowTemperatureRadiant:VariableFlow
- [x] Curve:DoubleExponentialDecay
- [x] Additional performance precision tradeoff modes https://github.com/NREL/EnergyPlus/pull/8121
- [x] Standardize Output Variable and Meter Fuel Types https://github.com/NREL/EnergyPlus/pull/8207
- [x] Construction:InternalSource

### New additions

- [ ] Native E+ CSV output https://github.com/NREL/EnergyPlus/pull/7904 (see https://github.com/NREL/OpenStudio/pull/4059)
  - [x] Add to SDK
  - [ ] Functional test in OpenStudio-resources

### Minor stuff

- [ ] Updates to FuelOil outputs? https://github.com/NREL/EnergyPlus/pull/8134
    - Note JM: This should have been done already, but need to make sure we captured everything.
- [x] Allow coal for Coil:Heating:Fuel https://github.com/NREL/EnergyPlus/pull/8123
- [x] ZoneProperty:UserViewFactors:BySurfaceName
- [ ] Fan:SystemModel
- [ ] Controller:WaterCoil
- [ ] EnergyManagementSystem:ProgramCallingManager
- [ ] Output:Table:SummaryReports
- [ ] Meter:Custom
- [ ] Meter:CustomDecrement

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4042
 - Update OpenStudio to use energyplus v9.4.0-IOFreeze

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Review by jmarrec — COMMENTED** [review]
Made some changes to get it building. We will need to update a windows i386 zip to the E+ release page for the nuget to work.

**Comment by jmarrec** [comment]
The E+ mac package cannot run a single simulation (I tried locally on the mac mini too, same)

```
jenkins@build ((7ddc6bccf...) *)$ cd resources/energyplus/Office_With_Many_HVAC_Types/
jenkins@Office_With_Many_HVAC_Types ((7ddc6bccf...) *)$ ls
Energy+.idd  eplustbl.htm epluszsz.csv in.epw       in.idf       screen.out
jenkins@Office_With_Many_HVAC_Types ((7ddc6bccf...) *)$ /Users/jenkins/git/OpenStudioIncremental/develop/build/EnergyPlus-9.4.0-908c5cedf5-Darwin-x86_64/energyplus
**FATAL:DLL problem cause program termination
libc++abi.dylib: terminating with uncaught exception of type EnergyPlus::FatalError: DLL problem cause program termination
Abort trap: 6

```

**Comment by jmarrec** [comment]
```
	164 - SqlFileFixture.TimeSeriesCount (Failed)
	168 - SqlFileFixture.AnnualTotalCosts (Child aborted)

```

**Comment by jmarrec** [comment]
Current reg test status as of c1a3ba9

image

**Comment by jmarrec** [comment]
TODO with things I can think of:

* [ ] Add FT test for `PerformancePrecisionTradeoff`
* [ ] Update FT tests for `OutputDebuggingData` (no longer numeric)
* [ ] FT test for `ConstructionWithInternalSource` ?
* [ ] VT for OS:Construction:InternalSource (inserted field)
* [ ] Update FT tests with new fields for ZoneHVACLowTempRadiantXXX
    * [ ] `ZoneHVACLowTempRadiantVarFlow`
    * [ ] `ZoneHVACLowTempRadiantConstFlow`
    * [ ] `ZoneHVACLowTempRadiantElectric`
* [ ] VT for OS:ZoneHVAC:LowTemperatureRadiant:XXX objects due to inserted fields
    * [ ] VT for `OS:ZoneHVAC:LowTemperatureRadiant:Electric`
    * [ ] VT for `OS:ZoneHVAC:LowTemperatureRadiant:ConstantFlow`
    * [ ] VT for `OS:ZoneHVAC:LowTemperatureRadiant:VariableFlow`

**Comment by jmarrec** [comment]
I had posted a script to compare IDDs on slack a while ago, so using it to easily know what VT to do:

```
[1] Test(main)> compare_idd("3.0.1", "OS:ZoneHVAC:LowTemperatureRadiant:Electric")
Fields that are been added from 3.0.1 to 3.1.0:
------------------------------------------------
* Setpoint Control Type * 6

Fields with changed indices from 3.0.1 to 3.1.0:
------------------------------------------------
* Heating Throttling Range - 6 => 7
* Heating Setpoint Temperature Schedule Name - 7 => 8
=> [#<OpenStudio::IddObject:0x0000560f2f17b148 @__swigtype__="_p_openstudio__IddObject">, #<OpenStudio::IddObject:0x0000560f2f1ffa88 @__swigtype__="_p_openstudio__IddObject">]
[2] Test(main)> compare_idd("3.0.1", "OS:ZoneHVAC:LowTemperatureRadiant:ConstantFlow")
Fields that are been added from 3.0.1 to 3.1.0:
------------------------------------------------
* Fluid to Radiant Surface Heat Transfer Model * 4
* Hydronic Tubing Outside Diameter * 6
* Hydronic Tubing Conductivity * 8
* Running Mean Outdoor Dry-Bulb Temperature Weighting Factor * 10
* Changeover Delay Time Period Schedule * 21

Fields with changed indices from 3.0.1 to 3.1.0:
------------------------------------------------
* Hydronic Tubing Inside Diameter - 4 => 5
* Hydronic Tubing Length - 5 => 7
* Temperature Control Type - 6 => 9
* Low Temp Radiant Constant Flow Heating Coil Name - 7 => 11
* Low Temp Radiant Constant Flow Cooling Coil Name - 8 => 12
* Rated Flow Rate - 9 => 13
* Pump Flow Rate Schedule Name - 10 => 14
* Rated Pump Head - 11 => 15
* Rated Power Consumption - 12 => 16
* Motor Efficiency - 13 => 17
* Fraction of Motor Inefficiencies to Fluid Stream - 14 => 18
* Number of Circuits - 15 => 19
* Circuit Length - 16 => 20
=> [#<OpenStudio::IddObject:0x0000560f2f0ee400 @__swigtype__="_p_openstudio__IddObject">, #<OpenStudio::IddObject:0x0000560f2f0d2e30 @__swigtype__="_p_openstudio__IddObject">]
[3] Test(main)> compare_idd("3.0.1", "OS:ZoneHVAC:LowTemperatureRadiant:VariableFlow")
Fields that are been added from 3.0.1 to 3.1.0:
------------------------------------------------
* Fluid to Radiant Surface Heat Transfer Model * 6
* Hydronic Tubing Outside Diameter * 8
* Hydronic Tubing Conductivity * 10
* Setpoint Control Type * 12
* Changeover Delay Time Period Schedule * 15

Fields with changed indices from 3.0.1 to 3.1.0:
------------------------------------------------
* Hydronic Tubing Inside Diameter - 6 => 7
* Hydronic Tubing Length - 7 => 9
* Temperature Control Type - 8 => 11
* Number of Circuits - 9 => 13
* Circuit Length - 10 => 14
=> [#<OpenStudio::IddObject:0x0000560f2f05c078 @__swigtype__="_p_openstudio__IddObject">, #<OpenStudio::IddObject:0x0000560f2f03cae8 @__swigtype__="_p_openstudio__IddObject">]
[4] Test(main)> compare_idd("3.0.1", "OS:Construction:InternalSource")
Fields that are been added from 3.0.1 to 3.1.0:
------------------------------------------------
* Two-Dimensional Temperature Calculation Position * 6

Fields with changed indices from 3.0.1 to 3.1.0:
------------------------------------------------
* Surface Rendering Name - 6 => 7
```

**Comment by jmarrec** [comment]
image

**Comment by jmarrec** [comment]
the refrigeration_system tests: running E+ in debug and breaking on ShowSevereError reveals the issue:

```
(const std::__cxx11::string) $0 = "<root>[Coil:WaterHeating:Desuperheater][Coil Water Heating Desuperheater 1] - Missing required property 'tank_name'."
```
The reg test is wrong and needs to be changed, cf: https://github.com/NREL/OpenStudio-resources/issues/113

the `lowtemprad` OSM tests are now passing with the added VT.

So does the `ems_1floor_SpaceType_1space`

**Comment by tijcolem** [comment]
Great work @joseph-robertson and @jmarrec. The only test CI is failing is on Mac. I replayed this manually a couple of times and it does fail repeatedly.  It appears to be related to precision/rounding issue specific to mac platform.  Assuming this in E+ 9.4 IOfreeze and not in our code?  This test passes fine on tip of develop with 9.3 E+ 

 ```
ctest -V -C Release -T test --rerun-failed --no-compress-output -R SqlFileFixture.AnnualTotalCosts
UpdateCTestConfiguration  from :/Users/jenkins/git/OpenStudioIncremental/develop/build/DartConfiguration.tcl
Parse Config file:/Users/jenkins/git/OpenStudioIncremental/develop/build/DartConfiguration.tcl
   Site: cbcis-Mac.local
   Build name: Darwin-c++
UpdateCTestConfiguration  from :/Users/jenkins/git/OpenStudioIncremental/develop/build/DartConfiguration.tcl
Parse Config file:/Users/jenkins/git/OpenStudioIncremental/develop/build/DartConfiguration.tcl
Test project /Users/jenkins/git/OpenStudioIncremental/develop/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 168
    Start 168: SqlFileFixture.AnnualTotalCosts

168: Test command: /Users/jenkins/git/OpenStudioIncremental/develop/build/Products/openstudio_utilities_tests "--gtest_filter=SqlFileFixture.AnnualTotalCosts"
168: Environment variables: 
168:  PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
168: Test timeout computed to be: 660
168: Running main() from gmock_main.cc
168: Note: Google Test filter = SqlFileFixture.AnnualTotalCosts
168: [==========] Running 1 test from 1 test suite.
168: [----------] Global test environment set-up.
168: [----------] 1 test from SqlFileFixture
168: [ RUN      ] SqlFileFixture.AnnualTotalCosts
168: /Users/jenkins/git/OpenStudioIncremental/develop/src/utilities/sql/Test/SqlFile_GTest.cpp:342: Failure
168: Expected equality of these values:
168:   ep_940.annualTotalUtilityCost
168:     Which is: 194908854.31999999
168:   sqlFile2.annualTotalUtilityCost().get()
168:     Which is: 194908854.33000001
168: /Users/jenkins/git/OpenStudioIncremental/develop/src/utilities/sql/Test/SqlFile_GTest.cpp:349: Failure
168: Expected equality of these values:
168:   ep_940.annualTotalCost_Water
168:     Which is: 3265714.9399999999
168:   sqlFile2.annualTotalCost(FuelType::Water).get()
168:     Which is: 3265714.9500000002
168: [  FAILED  ] SqlFileFixture.AnnualTotalCosts (739 ms)
168: [----------] 1 test from SqlFileFixture (739 ms total)
168: 
168: [----------] Global test environment tear-down
168: [==========] 1 test from 1 test suite ran. (742 ms total)
168: [  PASSED  ] 0 tests.
168: [  FAILED  ] 1 test, listed below:
168: [  FAILED  ] SqlFileFixture.AnnualTotalCosts
168: 
168:  1 FAILED TEST
1/1 Test #168: SqlFileFixture.AnnualTotalCosts ...***Failed    0.76 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.95 sec

The following tests FAILED:
	168 - SqlFileFixture.AnnualTotalCosts (Failed)
Errors while running CTest
```

**Comment by tijcolem** [comment]
I think we can go ahead and merge this and deal with that one issue on Mac.  From the sound of it, the E+ team is putting out new packages so we can test against those once they are available.

**Pull request merged**
