### PR TITLE
Preliminary fix for #1699, needs testing

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@axelstudios , @asparke2 is going to test then we will want to merge this into release

**Comment by macumber** [comment]
@nllong you may want to apply a similar fix to the server, I'm not sure if there is an equivalent place to do this?

**Comment by asparke2** [comment]
@macumber This now passes my test for EDAPT export.

**Comment by asparke2** [comment]
@macumber @axelstudios I merged this last bugfix, so I think it's really ready for 1.8.0

**Pull request merged**
