### PR TITLE
Fix #5248 - Typo in Schematron extension: .sch, not .sct!

### LINKED ISSUE #5248: Allow `.sch` extensions for schematron documents
Enhancement Request
--------------
Apparently schematron documents are supposed to have a `.sch` file extension. And that's what e.g. [BuildingSync uses](https://github.com/BuildingSync/use-cases/tree/main/BETTER/schematron). However, OpenStudio throws an error when validating that only `.xml` is allowed.

```
RuntimeError: /srv/jenkins/openstudio/docker-volumes/ubuntu-2204-nightly/Openstudio/src/utilities/xml/XMLValidator.cpp@188 : Schema path extension '.sch' not supported.
```

If it's a pain to support both, I don't have a problem renaming our Schematron docs to `.sch`.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5248

### Pull Request Author

 - [ ] All new and existing tests passes

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
@shorowit your error says you tried to call XMLValidator::validate("something.sch") but the link you shared is .xsd? which?

Also, couldn't you do that validation with whatever ruby or python external lib is doing?

**Comment by shorowit** [comment]
> @shorowit your error says you tried to call XMLValidator::validate("something.sch") but the link you shared is .xsd? which?

We are trying to validating something.sch (the schematron XML) against its XSD schema. Sorry, I could have linked to the schematron file too, it's [here](https://github.com/NREL/OpenStudio-HPXML/blob/schematron_sch/HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.sch).

> Maybe we should log warn when the extension of the file **to validate** is not XML and let it go to hell if it's not actually an xml file...

That'd be fine by me.

**Comment by jmarrec** [comment]
@wenyikuang FYI, I just rebooted the unix (2 ubuntus and the macos) with a temp cbci_jenkins_lib branch that will wipe the build dirs. Hopefully that'll solve a couple of weird build failures we're seeing on all PRs right now.

**Comment by jmarrec** [comment]
the locateOrCreateBinaryComment is malfunctioning for Ubuntu 24.04 at least. But anyways, wiping the build dir helped and I added the 24.04 deb / tar.gz links above @shorowit so you can test.

**Review by shorowit — APPROVED** [review]
Confirmed that it works in OS-HPXML, thanks!

**Pull request merged**
