### PR TITLE
Enable some new features supported by E+ 8.3

### PR DESCRIPTION
**Pull request by kbenne**
* Enhance SizingSystem with scalable sizing
* Add SizingPlant coincident sizing option
* Make DistrictHeating / Cooling ::nominalCapacity autosizable 
* Make HumidifierSteamElectric::ratedCapacity autosizable

### CODE REVIEW

**Comment by macumber** [comment]
@kbenne did you want me to review and merge this pull request?  I can if you want but just wanted to check first

**Comment by kbenne** [comment]
@macumber yes please review and merge.

**Comment by macumber** [comment]
@kbenne I'm not sure if these failures are specific to this branch or not but can you look into:

RubyTest-PATMeasures_Test-PATMeasures</Name>
[BOOST_ASSERT] &lt;2&gt; Assertion value failed on line 241 of double __cdecl openstudio::model::detail::SizingSystem_Impl::zoneMaximumOutdoorAirFraction(void) const in file E:\openstudio4\openstudiocore\src\model\SizingSystem.cpp.

AnalysisFixture.PatExportRun
[BOOST_ASSERT] &lt;2&gt; Assertion value failed on line 241 of double __cdecl openstudio::model::detail::SizingSystem_Impl::zoneMaximumOutdoorAirFraction(void) const in file E:\openstudio4\openstudiocore\src\model\SizingSystem.cpp.
Assertion failed: false, file e:\openstudio4\openstudiocore\src\model\../utilities/core/Assert.hpp, line 51

**Comment by kbenne** [comment]
I updated this branch and ran this test without issue.  The error you see is a symptom of the version translator not doing its job [here](https://github.com/NREL/OpenStudio/pull/1639/files#diff-3201e82200ae4bf36cd86ea3ba9adf16R2450), adding new required fields to SizingSystem.  I have a hunch that maybe your build wasn't complete.

One thing I do see on a regular basis with these ruby tests is

```
2115: MiniTest::Unit::TestCase is now Minitest::Test. From /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/testcase.rb:8:in `<module:Unit>'
2115: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:670:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
2115: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:255:in `<module:Unit>'
2115: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:9:in `<module:Test>'
2115: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:8:in `<top (required)>'
2115: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2115: 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2115: 	from /Users/kbenne/Development/OpenStudio/build/OSCore-prefix/src/OSCore-build/resources/ruleset/PATMeasures/CalibrationReports/tests/CalibrationReports_Test.rb:9:in `<top (required)>'
2115: 	from /Users/kbenne/Development/OpenStudio/openstudiocore/ruby/openstudio/ruleset/TestAllMeasuresInDir.rb:114:in `load'
2115: 	from /Users/kbenne/Development/OpenStudio/openstudiocore/ruby/openstudio/ruleset/TestAllMeasuresInDir.rb:114:in `block (2 levels) in <main>'
2115: 	from /Users/kbenne/Development/OpenStudio/openstudiocore/ruby/openstudio/ruleset/TestAllMeasuresInDir.rb:111:in `each'
2115: 	from /Users/kbenne/Development/OpenStudio/openstudiocore/ruby/openstudio/ruleset/TestAllMeasuresInDir.rb:111:in `block in <main>'
2115: 	from /Users/kbenne/Development/OpenStudio/openstudiocore/ruby/openstudio/ruleset/TestAllMeasuresInDir.rb:57:in `glob'
2115: 	from /Users/kbenne/Development/OpenStudio/openstudiocore/ruby/openstudio/ruleset/TestAllMeasuresInDir.rb:57:in `<main>'
2115: Testing measures found in '/Users/kbenne/Development/OpenStudio/build/OSCore-prefix/src/OSCore-build/resources/ruleset/PATMeasures'
2115: Testing /Users/kbenne/Development/OpenStudio/build/OSCore-prefix/src/OSCore-build/resources/ruleset/PATMeasures/CalibrationReports/
2115: Running measure test /Users/kbenne/Development/OpenStudio/build/OSCore-prefix/src/OSCore-build/resources/ruleset/PATMeasures/CalibrationReports//tests/CalibrationReports_Test.rb
```

**Comment by macumber** [comment]
@kbenne the minitest thing is really annoying, basically Ruby made some breaking changes to the built in test classes during the 2.0 series.  The current set up is the only one I've found that works (albeit with warnings) for all Ruby 2.0 versions.  This issue was related to this but I have made multiple commits on this:

https://github.com/NREL/OpenStudio/issues/1345

**Comment by macumber** [comment]
[utilities.idf.IdfObject] <1> IdfObject of type 'OS:EvaporativeCooler:Direct:Res
earchSpecial' cannot have field index of 10. Cutting off IdfObject field parsing
 here, with the following text remaining:

**Comment by kbenne** [comment]
@macumber thanks for looking.  I'll get to the bottom of it.

**Comment by kbenne** [comment]
This work is now part of https://github.com/NREL/OpenStudio/pull/1666 with version translations synchronized there.

**Pull request closed without merging**
