### PR TITLE
Add missing variable speed heat pump icons.

### LINKED ISSUE #1899: Crash when viewing plant loop on user model
I confirmed this on 1.9.1
https://unmethours.com/question/11836/crash-when-trying-to-view-hot-water-loop/

File is in unmethours post.

### PR DESCRIPTION
**Pull request by kbenne**
close #1899

### CODE REVIEW

**Comment by kbenne** [comment]
@DavidGoldwasser ping. simple icon add.

**Comment by DavidGoldwasser** [comment]
@kbenne, Thanks I saw this, My new mac I have home now isn't setup for builds yet, but I can build this on my PC at work on Monday morning, unless I just review icons without a build? Probably a bad habit. I'll try to fix and test the reporting measure schedule bug as well.

**Comment by DavidGoldwasser** [comment]
@kbenne this fixes the crash in my model "in.osm" from issue #1899 but the user model "BerthoudHall.osm" still crashes on the the hot water loop. Did you intend to fix that cash as well with this pull request, or will that be fixed elsewhere? I tested on Windows machine.

**Comment by kbenne** [comment]
I was attempting to explain that I thought this was two issues this morning before some $%^#$  (@brianlball ?) pulled the buzzer on me. Anyway I fixed the BerthoudHall model with a commit [here](https://github.com/NREL/OpenStudio/pull/1943).

**Comment by DavidGoldwasser** [comment]
Cool, then this is all set.

**Comment by DavidGoldwasser** [comment]
Thanks, didn't realize the other fix was outside of the branch.

**Pull request merged**
