### PR TITLE
V2.9.0 rc1

### PR DESCRIPTION
**Pull request by tijcolem**
This PR updates EnergyPlus: 
* from : https://github.com/NREL/EnergyPlus/releases/tag/v9.2.0-IOFreeze 
* to: https://github.com/NREL/EnergyPlus/releases/tag/v9.2.0-Alpha2

It also updates openstudio-gems.tar.gz for the new openstudio-standards, openstudio-extension and openstudio-workflow gem versions. 

I ran a full build and there are a few issues: 

1 ) Windows CI server hit an exceeded path limit of 260 chars due to the new paths in the openstudio-standards gem.  It looks like I can fix this by setting the reg key 'LongPathsEnabled' to 1 which then allows 4x the path lengths. Rebuilding now to see if that resolves it. Here was the error

`
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(974,5): error MSB4023: Cannot evaluate the item metadata "%(Extension)". The item metadata "%(Extension)" cannot be applied to the path "C:\Users\jenkins\git\OpenStudio\build\src\cli\embedded_files\ruby\2.2.0\gems\openstudio-standards-0.2.10.rc1\lib\openstudio-standards\standards\ashrae_90_1\ashrae_90_1_2004\comstock_ashrae_90_1_2004\data\comstock_ashrae_90_1_2004_refrigeration_system_lineup_json.cxx". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
`

2 )  One new unit test is failing. 
`169 - SqlFileFixture.AnnualTotalCosts (Failed)`

3 ) A few new regression test errors/failures. Assuming these are from the new e+ packages.  Here are the Linux results:

```
 **Failures** 
autosizedEvaporativeCondenserAirFlowRate failed for Coil Cooling DX Single Speed 1 of type CoilCoolingDXSingleSpeed
autosizedEvaporativeCondenserPumpRatedPowerConsumption failed for Coil Cooling DX Single Speed 1 of type CoilCoolingDXSingleSpeed
autosizedHighSpeedEvaporativeCondenserAirFlowRate failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed
autosizedHighSpeedEvaporativeCondenserPumpRatedPowerConsumption failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed
autosizedLowSpeedEvaporativeCondenserAirFlowRate failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed
autosizedLowSpeedEvaporativeCondenserPumpRatedPowerConsumption failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed

*** Methods that aren't implemented in C++ (but should be) ***

*** Missing Objects ***
F...............

Finished tests in 910.949008s, 0.2569 tests/s, 0.3194 assertions/s.


Error:
ModelTests#test_foundation_kiva_rb:
RuntimeError: Cannot find file /home/ubuntu/OpenStudio-resources/testruns/foundation_kiva.rb/in.osm
    /home/ubuntu/OpenStudio-resources/model_tests.rb:400:in `sim_test'
    /home/ubuntu/OpenStudio-resources/model_tests.rb:1384:in `test_foundation_kiva_rb'

Failure:
ModelTests#test_schedule_fixed_interval_2_osm [/home/ubuntu/OpenStudio-resources/model_tests.rb:258]
Minitest::Assertion: Expected: "Success"
  Actual: "Fail"

Failure:
ModelTests#test_schedule_file_osm [/home/ubuntu/OpenStudio-resources/model_tests.rb:258]
Minitest::Assertion: Expected: "Success"
  Actual: "Fail"

Failure:
ModelTests#test_schedule_file_rb [/home/ubuntu/OpenStudio-resources/model_tests.rb:258]
Minitest::Assertion: Expected: "Success"
  Actual: "Fail"

Error:
ModelTests#test_intersect_356_osm:
RuntimeError: Exit code 1:
[openstudio.model.Surface] <1> Initial area of surface 'Surface 909' 161.303 does not equal post intersection area 161.303
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 133' 248.051 does not equal post intersection area 248.051
[openstudio.model.Surface] <1> Initial area of surface 'Surface 922' 152.729 does not equal post intersection area 152.729
Initial area of surface 'Surface 909' 161.303 does not equal post intersection area 161.303
Initial area of other surface 'Surface 133' 248.051 does not equal post intersection area 248.051
Initial area of surface 'Surface 922' 152.729 does not equal post intersection area 152.729

Error: Incorrect messages detected
Backtrace:
        /home/ubuntu/OpenStudio-resources/testruns/intersections/356.osm/intersect.rb:45:in `<top (required)>'
        eval:107:in `require'
        eval:107:in `require'
        :/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        :/openstudio_cli.rb:1511:in `execute'
        :/openstudio_cli.rb:763:in `execute'
        :/openstudio_cli.rb:1746:in `<main>'
        eval:116:in `eval'
        eval:116:in `require_embedded_absolute'
        eval:101:in `block in require'
        eval:95:in `each'
        eval:95:in `require'
        eval:3:in `<main>'
Exception: Incorrect messages detected
<main>: unexpected return

    /home/ubuntu/OpenStudio-resources/model_tests.rb:164:in `block in run_command'
    :/ruby/2.2.0/open3.rb:199:in `popen_run'
    :/ruby/2.2.0/open3.rb:93:in `popen3'
    /home/ubuntu/OpenStudio-resources/model_tests.rb:148:in `run_command'
    /home/ubuntu/OpenStudio-resources/model_tests.rb:473:in `intersect_test'
    /home/ubuntu/OpenStudio-resources/model_tests.rb:2060:in `test_intersect_356_osm'

Failure:
ModelTests#test_schedule_fixed_interval_osm [/home/ubuntu/OpenStudio-resources/model_tests.rb:258]
Minitest::Assertion: Expected: "Success"
  Actual: "Fail"

Failure:
ModelTests#test_autosizing_rb [/home/ubuntu/OpenStudio-resources/model_tests.rb:781]
Minitest::Assertion: 6 autosizedFoo methods failed to return a value:
autosizedEvaporativeCondenserAirFlowRate failed for Coil Cooling DX Single Speed 1 of type CoilCoolingDXSingleSpeed
autosizedEvaporativeCondenserPumpRatedPowerConsumption failed for Coil Cooling DX Single Speed 1 of type CoilCoolingDXSingleSpeed
autosizedHighSpeedEvaporativeCondenserAirFlowRate failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed
autosizedHighSpeedEvaporativeCondenserPumpRatedPowerConsumption failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed
autosizedLowSpeedEvaporativeCondenserAirFlowRate failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed
autosizedLowSpeedEvaporativeCondenserPumpRatedPowerConsumption failed for Coil Cooling DX Two Speed 1 of type CoilCoolingDXTwoSpeed..
Expected: 0
  Actual: 6

234 tests, 291 assertions, 5 failures, 2 errors, 0 skips`
```

### CODE REVIEW

**Comment by tijcolem** [comment]
link to full build ci run. 
https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-develop-nightly/detail/openstudio-develop-nightly/149/pipeline

**Comment by jmarrec** [comment]
1) came up before on local machines i think

2) this one definitely came up before, and is weird because you don't get the same result on windows v linux due to rounding error, I'll investigate and fix

3) the schedule osm tests are supposed to not exist, I haven't pushed a few commits that do so but will this morning. Autosizing test is because of newly deprecated methods following renaming I think, I'll fix that
The schedule fixed rb tests and kiva not sure, but I'll fix these

**Comment by jmarrec** [comment]
I ran the regression tests using 06d308c:

```
Finished tests in 2459.817351s, 0.0943 tests/s, 0.1187 assertions/s.


Error:
ModelTests#test_intersect_356_osm:
RuntimeError: Exit code 1:
[openstudio.model.Surface] <1> Initial area of surface 'Surface 907' 161.303 does not equal post intersection area 161.303
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 133' 248.051 does not equal post intersection area 248.051
[openstudio.model.Surface] <1> Initial area of surface 'Surface 920' 152.729 does not equal post intersection area 152.729
Initial area of surface 'Surface 907' 161.303 does not equal post intersection area 161.303
Initial area of other surface 'Surface 133' 248.051 does not equal post intersection area 248.051
Initial area of surface 'Surface 920' 152.729 does not equal post intersection area 152.729

Error: Incorrect messages detected
Backtrace:
	/home/julien/Software/Others/OpenStudio-resources/testruns/intersections/356.osm/intersect.rb:45:in `<top (required)>'
	eval:107:in `require'
	eval:107:in `require'
	:/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	:/openstudio_cli.rb:1511:in `execute'
	:/openstudio_cli.rb:763:in `execute'
	:/openstudio_cli.rb:1746:in `<main>'
	eval:116:in `eval'
	eval:116:in `require_embedded_absolute'
	eval:101:in `block in require'
	eval:95:in `each'
	eval:95:in `require'
	eval:3:in `<main>'
Exception: Incorrect messages detected
<main>: unexpected return

    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:164:in `block in run_command'
    :/ruby/2.2.0/open3.rb:199:in `popen_run'
    :/ruby/2.2.0/open3.rb:93:in `popen3'
    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:148:in `run_command'
    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:473:in `intersect_test'
    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:2062:in `test_intersect_356_osm'

232 tests, 292 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by jmarrec** [comment]
foundation_kiva was unfortunately modified to add methods that don't exist in 2.8.1 and below, while it's an existing test. This breaks backward compatibility. cf https://github.com/NREL/OpenStudio-resources/pull/72#issuecomment-532182212

**Comment by jmarrec** [comment]
I ran the regression tests with 2.9.0. I also performed the three-way analysis:
* Running in OS 2.8.1 / E+ 9.1.0
* Take IDFs generated by OS 2.8.1 and Transition IDFs output from 9.1.0 to 9.2.0-Alpha2. Run these
* Running in OS 2.9.0 / E+ 9.2.0 Alpha2

This release is a lot more stable than the last time we had a release than bumped the E+ version. A few highlights:

image


image

image


The three-way analysis shows that most of these small diffs are inherent to EnergyPlus itself:

image


image

**Comment by jmarrec** [comment]
OpenStudio-standards directory tree is really problematic.

```
$ cd openstudio-standards
$ find . -type f -name "*.json" -print|awk '{print length($0), $0}' | sort -n
...
130 ./test/90_1_prm/output/Turkevi-baseline_for_EN1rev4_Feb_14th-90.1-2010-ASHRAE 169-2006-4A-/final_2.4.1/run/measure_attributes.json
139 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/comstock_ashrae_90_1_2004/data/comstock_ashrae_90_1_2004.space_types.json
139 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/comstock_ashrae_90_1_2007/data/comstock_ashrae_90_1_2007.space_types.json
139 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/comstock_ashrae_90_1_2010/data/comstock_ashrae_90_1_2010.space_types.json
139 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/comstock_ashrae_90_1_2013/data/comstock_ashrae_90_1_2013.space_types.json
139 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.space_types.json
142 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.space_types.json
145 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/comstock_ashrae_90_1_2004/data/comstock_ashrae_90_1_2004.exterior_lighting.json
145 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/comstock_ashrae_90_1_2007/data/comstock_ashrae_90_1_2007.exterior_lighting.json
145 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/comstock_ashrae_90_1_2010/data/comstock_ashrae_90_1_2010.exterior_lighting.json
145 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/comstock_ashrae_90_1_2013/data/comstock_ashrae_90_1_2013.exterior_lighting.json
145 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.exterior_lighting.json
146 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/comstock_ashrae_90_1_2004/data/comstock_ashrae_90_1_2004.refrigerated_cases.json
146 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/comstock_ashrae_90_1_2007/data/comstock_ashrae_90_1_2007.refrigerated_cases.json
146 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/comstock_ashrae_90_1_2010/data/comstock_ashrae_90_1_2010.refrigerated_cases.json
146 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/comstock_ashrae_90_1_2013/data/comstock_ashrae_90_1_2013.refrigerated_cases.json
146 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.refrigerated_cases.json
148 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.exterior_lighting.json
149 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.refrigerated_cases.json
155 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/comstock_ashrae_90_1_2004/data/comstock_ashrae_90_1_2004.refrigeration_system_lineup.json
155 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/comstock_ashrae_90_1_2007/data/comstock_ashrae_90_1_2007.refrigeration_system_lineup.json
155 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/comstock_ashrae_90_1_2010/data/comstock_ashrae_90_1_2010.refrigeration_system_lineup.json
155 ./lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/comstock_ashrae_90_1_2013/data/comstock_ashrae_90_1_2013.refrigeration_system_lineup.json
155 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.refrigeration_system_lineup.json
158 ./lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.refrigeration_system_lineup.json
```

**Comment by tijcolem** [comment]
That is a really nice detailed breakdown showing the 3-way analysis between Openstudio/E+ versions! 
It looks like we are on the right track, as you pointed out, most of the differences lie within E+ itself. 

As for a recap of the issues previously listed: 

1 ) Setting the LongPathsEnabled=1 in the Windows regedit did not work and I still hit the path chars exceeded. Rather than fiddling with windows getting this to work, I set the CI pipeline to build in the /c/ root path and that did work (prob by a few chars).   see: https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-develop-nightly/detail/openstudio-develop-nightly/153/pipeline 

I also installed the OpenStudio-2.9.0.exe installer package into the default location (c:/openstudio-2.9.0), and a less common user directory that occupies more path space, and they both installed okay. I'm unsure sure if Windows throws an error about path size issue on installation vs run-time.  Either way, I think openstudio-standards should trim paths where it makes sense to conserve space.  I suppose building OpenStudio in the /c/ root directory could be a work-around until this resolved.  Thanks for putting in issue to openstudio-standards. They are aware and working on a fix. 

2 )  Yep, that resolved the unit test failures in run: https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-develop-nightly/detail/openstudio-develop-nightly/153/pipeline 

3 )  I used the latest builds from commit [06d308c](https://github.com/NREL/OpenStudio/pull/3677/commits/06d308cdc40b025d9f94b4985bf6e5bdc0afaeab) to re-run the regression tests and it looks much improved although I did see that test_schedule_file_rb did pop up (using ubuntu 16.04). I can re-run the reg tests again to confirm. Thanks for resolving the other issues. I know that the intersect failures are an ongoing issue so will ignore those. 

```
$ $ openstudio openstudio_version 
2.9.0.06d308cdc4
......
Finished tests in 1292.024714s, 0.1803 tests/s, 0.2268 assertions/s.
Failure:
ModelTests#test_schedule_file_osm [/home/ubuntu/Openstudio-resources/model_tests.rb:258]
Minitest::Assertion: Expected: "Success"
  Actual: "Fail"

Error:
ModelTests#test_intersect_356_osm:
RuntimeError: Exit code 1:
[openstudio.model.Surface] <1> Initial area of surface 'Surface 909' 161.303 does not equal post intersection area 161.303
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 133' 248.051 does not equal post intersection area 248.051
[openstudio.model.Surface] <1> Initial area of surface 'Surface 922' 152.729 does not equal post intersection area 152.729
Initial area of surface 'Surface 909' 161.303 does not equal post intersection area 161.303
Initial area of other surface 'Surface 133' 248.051 does not equal post intersection area 248.051
Initial area of surface 'Surface 922' 152.729 does not equal post intersection area 152.729

Error: Incorrect messages detected
Backtrace:
        /home/ubuntu/Openstudio-resources/testruns/intersections/356.osm/intersect.rb:45:in `<top (required)>'
        eval:107:in `require'
        eval:107:in `require'
        :/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        :/openstudio_cli.rb:1511:in `execute'
        :/openstudio_cli.rb:763:in `execute'
        :/openstudio_cli.rb:1746:in `<main>'
        eval:116:in `eval'
        eval:116:in `require_embedded_absolute'
        eval:101:in `block in require'
        eval:95:in `each'
        eval:95:in `require'
        eval:3:in `<main>'
Exception: Incorrect messages detected
<main>: unexpected return

    /home/ubuntu/Openstudio-resources/model_tests.rb:164:in `block in run_command'
    :/ruby/2.2.0/open3.rb:199:in `popen_run'
    :/ruby/2.2.0/open3.rb:93:in `popen3'
    /home/ubuntu/Openstudio-resources/model_tests.rb:148:in `run_command'
    /home/ubuntu/Openstudio-resources/model_tests.rb:473:in `intersect_test'
    /home/ubuntu/Openstudio-resources/model_tests.rb:2072:in `test_intersect_356_osm'

Failure:
ModelTests#test_schedule_file_rb [/home/ubuntu/Openstudio-resources/model_tests.rb:258]
Minitest::Assertion: Expected: "Success"
  Actual: "Fail"

233 tests, 293 assertions, 2 failures, 1 errors, 0 skips
```

I think at this point we are just waiting to see to openstudio-standards can shorten the paths for Windows.  We should know more tomorrow on that.

**Pull request merged**
