### PR TITLE
Improvements to the class generator

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
This removes the setters taking optional in the impl classes, passes strings by const ref, better identifies schedule fields

@jmarrec can you remember any other issues you had with the class generator?  anything that was particularly annoying or confusing to fix?

**Comment by jmarrec** [comment]
Not off the top of head no, but I need to add `ElectricLoadCenter:Storage:Converter`, so I can merge this into my branch and try it. I'll keep an eye out for problems.

**Comment by jmarrec** [comment]
Should be able to fix these:

// TODO: Check the following class names against object getters and setters.
class Schedule;
class UniVariateCurves; //replace with Curve;
class Zone; // replace with ThermalZone

**Comment by jmarrec** [comment]
The .cpp class also ends up with the setXXX methods having a type "void" while they clearly return a bool

**Comment by jmarrec** [comment]
Need to delete the Q_OBJECT reference

```
  class MODEL_API XXXXXX_Impl : public ParentObject_Impl {
    Q_OBJECT;
   public:
```

**Comment by jmarrec** [comment]
@macumber maybe reopen this one?

**Pull request merged**
