### PR TITLE
90298376 results viewer update

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@axelstudios this should make 1.7.0

**Comment by macumber** [comment]
Not done yet

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/issues/1518

**Comment by macumber** [comment]
@axelstudios this is ready for testing now, can you try it out on Linux?  @kbenne can you try it on Mac?  @rpg777 can you try it out with radiance results?

**Comment by macumber** [comment]
It is still slower but I will wait on that until I am done with https://github.com/NREL/OpenStudio/pull/1530

**Comment by kbenne** [comment]
@macumber ok.

**Comment by rpg777** [comment]
OK, using Radiance data: 
* I can step though the data with no crashes
* The floodplots look correct (and awesome):
Got Window Group Illuminance? =)

BUT:
* timesteps with all zero values have white flood plots instead of blue ones, still:
zero-value floodplot

**Comment by macumber** [comment]
Thanks @DavidGoldwasser and @rpg777 my last commits change the appearance quite a bit so you should check it out, basically I am only rendering at the resolution of the data which improves performance and is arguably more "real"

**Comment by macumber** [comment]
@DavidGoldwasser the slider weirdness for illuminance maps is due to https://github.com/NREL/OpenStudio/issues/1525 and is present in 1.6.0

There is slider weirdness for floodplots which is new though, the span slider starts out at 0 now when it used to start out fully maximized.  I might file a minor bug and let that go for now though, what do you think?

**Comment by macumber** [comment]
I changed to rendering at twice resolution of illuminance maps density, we can discuss the right thing to do later

**Comment by rpg777** [comment]
Looks good to me, Dan. I totally agree with the resolution rendering, it allows the user to appreciate the "quality" of their spatial data. The default smoothing obfuscates this unless you're really looking for it. 
flood plot, 1/2 grid spacing resolution

**Comment by kbenne** [comment]
@macumber I'm not exactly sure what I need to be testing here, but I did compile it and fire up RV.  Worked fine on detailed time series line plots and flood plots.  This is the kind of stuff I normally use it for.  I didn't do any illuminance maps, but I figure Rob probably has that covered.

**Comment by DavidGoldwasser** [comment]
@macumber I'm still seeing a crash this morning after overnight build, but I'm using a previously run simulation, wondering if that matters?

**Comment by kbenne** [comment]
What are you testing @DavidGoldwasser?  I just pointed it at some old regression test results from over in OpenStudio-resources.

**Comment by macumber** [comment]
Thanks @kbenne I just wanted some testing on Mac to make sure the update to the new Qwt version was working on Mac, if you can do line plots and flood plots on Mac and things seem fine that's all we need to check

**Comment by rpg777** [comment]
@macumber @kbenne, I loaded an eplusout.sql on my Mac, looked at a few line plots and some more flood plots, and that all looks fine too. @kbenne you probably don't need to do anything.

**Comment by DavidGoldwasser** [comment]
@kbenne I'm going to test an E+ run with illuminance maps in ResultsViewer. I mistakenly build develop last night, I'm building the correct branch this morning.

**Comment by DavidGoldwasser** [comment]
@macumber The crash is gone when I use the branch now. I still do see a white screen with "NO DATA" vs. a blue background if i go to a time where there is no data.@rpg777 seems to see blue in this situation. Maybe this is not a mac vs. PC but becuase my map came from E+ run vs. Radiance?

**Comment by macumber** [comment]
@DavidGoldwasser yes that is radiance vs E+ runs, that is working as designed

**Comment by macumber** [comment]
Thanks all, sounds like this is good to go, I'm going to merge to develop.  @axelstudios can you do some testing with ResultsViewer on Linux once you make the packages?

**Pull request merged**
