### PR TITLE
Adds symlinks to openstudio-standards gem for Mac

### PR DESCRIPTION
**Pull request by asparke2**
@evanweaver I think the only way to test this change is to create and run an installer on Mac.  Can you create one and @DavidGoldwasser will test?

### CODE REVIEW

**Comment by macumber** [comment]
@kbenne you have any thoughts on this?

**Comment by asparke2** [comment]
@macumber @kbenne is the one who suggested this.  I don't know bout no symlinks.

**Comment by macumber** [comment]
Hehe ok by me :-)

**Comment by kbenne** [comment]
Well this was basically my suggestion. One thing @mbadams5 and I were talking about is how this plays out on el capitan with tighter security. I think the general idea is ok as a bandaid, but maybe we should be linking into some site_ruby directory instead. We've already been linking openstudio.rb for years so...

**Comment by evanweaver** [comment]
Let's give it a shot.

**Pull request merged**
