### PR TITLE
Fix #2874 - .deb package install to /usr/local/openstudio-x.y.z instead of /usr/

### LINKED ISSUE #2874: Wrong OSApp shared components (resources) install path on Linux
I've used the docker-openstudio image to run OpenStudioApp (version 2.2.2) and have found that the Resources, Ruby, EnergyPlus, Examples and Radiance OSApp folders, as well as the OpenStudio release notes pdf file, are installed in the `/usr` dir, instead of the `/usr/share/openstudio-$OPENSTUDIO_APP_VERSION/OSApp` dir which is the path the `OpenStudioApp::resourcesPath()` method expects to be able to find all resources.

Also, the ApplicationPathHelpers.cxx.in source file (in core/utils) uses as resource dir for linux the following candidate path:

`candidate = getApplicationRunDirectory().parent_path() / openstudio::toPath("share/openstudio-" + openStudioVersion() + "");`

which differs in the `OSApp` suffix from the OpenStudioApp::resourcesPath method. Apparently, these methods should lead to the same path.

(To be able to run the OpenStudioApp you also have to install the `libnss3 libXcursor1 libxcomposite1 libasound2 libxtst6` packages)

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #2874 (a very annoying long term issue for me).

I built CPACK_BINARY_DEB and checked that .deb installs correctly to `/usr/local/opensudio-x.y.z`

**Still left to do:**

- [x] Name package `openstudio-x.y.z` instead of `openstudio` to allow several versions to be installed on the same system (currently apt/dpkg will just overwrite completely the previous version)

- [x] Add symlink of CLI to `/usr/local/bin/`

### CODE REVIEW

**Comment by jmarrec** [comment]
Named the debian package with version to allow several versions installed. Adding description and homepage. Still struggling with the symlink to the CLI...

```
(py36)julien@OS-build2$ dpkg-deb -I OpenStudio-2.5.0.7a496a5ab4-Linux.deb 
 new debian package, version 2.0.
 size 284463110 bytes: control archive=24773 bytes.
     390 bytes,    11 lines      control              
   89303 bytes,   815 lines      md5sums              
 Package: openstudio-2.5.0
 Version: 2.5.0
 Section: devel
 Priority: optional
 Architecture: amd64
 Depends: libwxgtk3.0-0
 Homepage: https://www.openstudio.net
 Installed-Size: 1187667
 Maintainer: openstudio@nrel.gov
 Description: OpenStudio is a cross-platform collection of software tools to support whole building energy modeling using EnergyPlus and advanced daylight analysis using Radiance
```

**Comment by macumber** [comment]
@nllong @rHorsey @evanweaver this pr affects you guys more than me

**Comment by jmarrec** [comment]
For the docker stuff the only difference would be to change the ENV variable RUBYLIB. I suppose we could also symlink openstudio.rb/so so nothing needs to change. I’m all ears here.

In case it wasn’t clear enough, as a multi platform user (I have multiple oses: windows, Mac, and now most of time Ubuntu), Linux has been really left behind in terms of usability and I’d like to bridge that gap, for myself obviously, but other Linux users too.

——
Sent from a mobile device, please excuse the brevity.
Julien Marrec, EBCP, BPI MFBA
Owner


Direct: +33 6 95 14 42 13
Website: www.effibem.com

LinkedIn (en) | (fr)

**Comment by nllong** [comment]
Looks good. As long as it is /usr/local/openstudio-2.5.0 and not /usr/local/openstudio-2.5.0.abcd1234 then I am okay with it. I think a symlink would be nice.

**Comment by nllong** [comment]
perfect then. I think we will be okay with non symlinking anything. merci
for the items that will need to change.

**Comment by jmarrec** [comment]
I've been struggling trying to add some of features that will make it into an actual app, I think it's mostly working though there are a few commands I cannot figure out how to run on install so manually doing it now, at least `sudo xdg-mime install --novendor --mode system /usr/share/mime/application/x-openstudio.xml` (potentially a couple more, I keep trying and trying to my caches may have the past info from an earlier try... would need a fresh machine to test it).

Anyways, here are the features in action:

**desktop entry allows searching for the OS App (and has icons):**

image

**New mime type for OSM files with icons, clicking on OSM launches OS App:**
image

**Comment by pachi** [comment]
This is very nice, @jmarrec !
I've a suggestion, to improve usability  (of parallel installed versions): adding links to the versioned binaries, so all installed versions are available, though the last installed wins as the default binary (unversioned one).

This is the corresponding (untested) code for openstudiocore/CMakeLists.txt, based on your PR:

# Add an arbitrary link (broken) at build/openstudio (if build/ is your build folder) that already points to the **installed** /usr/local/openstudio-x.y.z/bin/openstudio-${OpenStudio_VERSION}
execute_process(COMMAND ln -sf ${CPACK_INSTALL_PREFIX}bin/openstudio openstudio-${OpenStudio_VERSION})
# Have this link be installed with the .deb package in /usr/local/bin
install(FILES ${CMAKE_BINARY_DIR}/openstudio-${OpenStudio_VERSION} DESTINATION /usr/local/bin COMPONENT CLI)
# Same for OpenStudioApp
execute_process(COMMAND ln -sf ${CPACK_INSTALL_PREFIX}bin/OpenStudioApp OpenStudioApp-${OpenStudio_VERSION})
# Have this link be installed with the .deb package in /usr/local/bin
install(FILES ${CMAKE_BINARY_DIR}/OpenStudioApp-${OpenStudio_VERSION} DESTINATION /usr/local/bin COMPONENT CLI)

**Comment by pachi** [comment]
Yes, and also the corresponding two links to OpenStudioApp. That is, keep the links your PR already added, and include the versioned ones.

**Pull request merged**
