### PR TITLE
Native extensions

### PR DESCRIPTION
**Pull request by kbenne**
Pull request overview
---------------------

 - Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by kbenne** [comment]
@tijcolem this corresponds with the "native-extensions" branch of openstudio-gems repo. We will need to rebuild the os gem, upload to s3, and then update the openstudio-gems filename and checksum here in the OpenStudio project.

**Comment by tijcolem** [comment]
@kbenne I updated the openstudio3-gems in the CMakeList.txt and tested each OpenStudio incremental installer for Windows, Mac, and Linux to verify if pycall gem works as expected. 

I used the ruby test.rb file you used previously: 
```
require 'pycall/import'
include PyCall::Import
pyimport :math
puts math.sin(math.pi / 4) - Math.sin(Math::PI / 4)   # => 0.0
```

**Results**

Mac
```
/Applications/OpenStudio-3.0.0-rc1/bin/openstudio test.rb  
0.0
```
Linux
```
ubuntu@ip-172-18-9-124:~$ openstudio test.rb 
0.0
```

Windows: 
```
PS C:\Users\Administrator> C:\openstudio-3.0.0-rc1\bin\openstudio.exe .\test.rb
python: can't open file ':/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall/python/investigator.py': [Errno 22] Invalid argument
Error executing argv: []
Error: PyCall::PythonNotFound in :/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall/libpython/finder.rb:36:in `find_python_config'
:/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall/libpython/finder.rb:41:in `find_libpython'
:/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall/init.rb:35:in `init'
:/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall/init.rb:16:in `const_missing'
:/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall.rb:62:in `import_module'
:/ruby/2.5.0/bundler/gems/pycall.rb-683831357718/lib/pycall/import.rb:18:in `pyimport'
C:/Users/Administrator/test.rb:3:in `<top (required)>'
eval:113:in `require'
eval:113:in `require'
:/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
:/openstudio_cli.rb:1509:in `execute'
:/openstudio_cli.rb:763:in `execute'
:/openstudio_cli.rb:1746:in `<main>'
eval:133:in `eval'
eval:133:in `require_embedded_absolute'
eval:106:in `block in require'
eval:100:in `each'
eval:100:in `require'
eval:3:in `<main>'
```

The above windows error could be related to my windows python environment and not necessary the embedded pycall gem.  Also, to build an msvc openstudio3-gems with native pycall gem, I had to modify the pycall ruby_wrapper.c as the VS compiler threw an error:
```error C2099: initializer is not a constant.```
This commit resolved that error: 
https://github.com/tijcolem/pycall.rb/commit/683831357718a95a6cdb6c050759a40d8050790e

I tried to setting RUBY_TYPED_FREE_IMMEDIATELY=0 but that made no difference. Seems the VS c compiler is more strict and doesn't allow for this? Someone with more Windows-specific C experience can probably answer this. 

Maybe we add another native gem (protobuf?) to [OpenStudio-gems](https://github.com/NREL/OpenStudio-gems ) that doesn't require any other system dependency and verify it works on Windows, Linux and Mac before we merge?

**Comment by tijcolem** [comment]
looks like I made a mistake when updating the pycall gem for the windows compiler error. I forked a copy of https://github.com/NREL/pycall.rb but did not merge in the changes for the finder. 

I need to rebuild the windows openstudio-gems and try this again.  I'll report back.

**Comment by tijcolem** [comment]
okay, the latest window test with new openstudo3-gems. 

 C:\openstudio-3.0.0-rc1\bin\openstudio.exe .\test.rb
-1.1102230246251565e-16

So pycall on windows is indeed working. notice the ever slight difference between ruby vs python output. 
```
require 'pycall/import'
include PyCall::Import
pyimport :math
puts math.sin(math.pi / 4) 
puts Math.sin(Math::PI / 4)
puts math.sin(math.pi / 4) - Math.sin(Math::PI / 4)   # => 0.0
```
PS C:\Users\Administrator\Desktop> C:\openstudio-3.0.0-rc1\bin\openstudio.exe .\test.rb
0.7071067811865475
0.7071067811865476
-1.1102230246251565e-16

Caulk it up to the inexact real number handling and round off between ruby vs python on windows.  

So looks like we are good to go with this now. I need to tidy up the windows openstudio-gem build process but we should be good to merge this PR.

**Pull request merged**
