### PR TITLE
All nano signals must be detached in object desctructors, the nano si…

### PR DESCRIPTION
**Pull request by macumber**
…gnals still fire even if the receiver has been deleted

### CODE REVIEW

**Comment by macumber** [comment]
@evanweaver can you review and merge?  we might have more of these cases out there to fix?

@mbadams5 FYI

**Comment by kbenne** [comment]
What symptom motivated you to do this? There must have been some issue to get you looking into this. Performance maybe?

**Comment by ljbrackney** [comment]
Based on the commit I'm guessing it's related to the utility bill crash bug.

On Jun 13, 2017, at 7:55 PM, Kyle Benne <notifications@github.com<mailto:notifications@github.com>> wrote:


What symptom motivated you to do this? There must have been some issue to get you looking into this. Performance maybe?

**Comment by macumber** [comment]
Oh yeah, forgot to link to the issue, this fixes https://github.com/NREL/OpenStudio/issues/2634

This was a nasty little one to track down

**Pull request merged**
