### PR TITLE
Fuel cell fix

### PR DESCRIPTION
**Pull request by brianlball**
Adds ElectricLoadCenterDistribution to all Generator Constructors. Without, causes crash in E+ (https://github.com/NREL/EnergyPlus/issues/6789)

Blocker for FuelCell project.

All relevant tests pass (including resource tests)

these unrelated tests failed:
model tests:
[ FAILED ] ModelFixture.CoilHeatingDesuperheater_addToNode
Energyplus tests:
[ FAILED ] EnergyPlusFixture.ErrorFile_WarningsAndSevere
[ FAILED ] EnergyPlusFixture.ErrorFile_WarningsAndCrash
[ FAILED ] EnergyPlusFixture.ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted
[ FAILED ] EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_Hourly_Shifted
[ FAILED ] EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_500_Shifted
[ FAILED ] EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_DaysTimeSeries

### CODE REVIEW

**Comment by lgentile** [comment]
I am proud of you @brianlball ! Well done!

**Comment by jmarrec** [comment]
Hey guys, I'm just stumbling on to this PR. I find it quite weird and unexpected that the Generator objects would instantiate an `ElectricLoadCenterDistribution` object.

The user should be the one responsible to place the generator on the ELCD of their choice.

To make a parallel: I wouldn't expect instantiation of a `Surface` to create a `Space` to hold it just because it's required.

In particular, I often put several generator objects on the same ELCD, for eg:

```
m = Model.new
gen1 = GeneratorMicroTurbine.new(m)
gen2 = GeneratorMicroTurbine.new(m)
gen3 = GeneratorMicroTurbine.new(m)

elcd = ElectricLoadCenterDistribution.new(m)
elcd.addGenerator(gen1)
elcd.addGenerator(gen2)
elcd.addGenerator(gen3)

m.getElectricLoadCenterDistributions.size
=> 4
```

So now I have 3 left over ELCDs in my model. Sure they won't be translated, but still.

**Comment by macumber** [comment]
I agree but didn't have time to suggest a better version, @brianlball had some specific use cases that made this easier for him, I don't recall what they were

**Comment by brianlball** [comment]
The issue @macumber is referring to is that the Fuel Cell generator would hard crash in E+ if there was no ELCD and there was no way to add it in the GUI.

**Pull request merged**
