### PR TITLE
Fix #3872 - Add OutputDiagnostics, OutputDebuggingData and OutputJSON to model SDK

### LINKED ISSUE #3872: Adding advanced output variables to sdk
"Do you know if os is supporting adding advanced output variables, eg. https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-thermal-zone-description-geometry.html#additional-window-outputs-advanced ? I looked up in sdk docs, without luck to find a similar functionality. In E+, if we add an object of : Output:Diagnostics,DisplayAdvancedReportVariables , E+will know we want those additional variables, and allow specifying those variables in Output:Variable objects."

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3872

I took this as an opportunity to refresh my branch that automates FT/RT and Model GTest, cf #3876. Thought I'd kill two birds with one stone here.

**Note** I still need FT tests, RT tests and regression tests.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
https://ci.commercialbuildings.dev/blue/rest/organizations/jenkins/pipelines/openstudio-incremental-develop/branches/PR-3875/runs/2/nodes/7/steps/91/log/?start=0

```
D:\jenkins\openstudio\develop\build\src\utilities\csharp_OpenStudioUtilitiesIdd_wrap.cxx(293296): error C2039: 'Output_DiagnosticsFields': is not a member of 'openstudio' [D:\jenkins\openstudio\develop\build\csharp\openstudio_csharp.vcxproj]
  D:\jenkins\openstudio\develop\build\src\utilities/idd/OS_PlantComponent_UserDefined_FieldEnums.hxx(36): note: see declaration of 'openstudio'
D:\jenkins\openstudio\develop\build\src\utilities\csharp_OpenStudioUtilitiesIdd_wrap.cxx(293296): error C2065: 'Output_DiagnosticsFields': undeclared identifier [D:\jenkins\openstudio\develop\build\csharp\openstudio_csharp.vcxproj]
D:\jenkins\openstudio\develop\build\src\utilities\csharp_OpenStudioUtilitiesIdd_wrap.cxx(293296): error C2065: 'result': undeclared identifier [D:\jenkins\openstudio\develop\build\csharp\openstudio_csharp.vcxproj]
D:\jenkins\openstudio\develop\build\src\utilities\csharp_OpenStudioUtilitiesIdd_wrap.cxx(293300): error C2065: 'result': undeclared identifier [D:\jenkins\openstudio\develop\build\csharp\openstudio_csharp.vcxproj]
```

I built locally, can't reproduce... (I used Ninja though)

**Comment by jmarrec** [comment]
I'm building MSVC to try to reproduce. I have a lead though: I modified E+ Output:Diagnostics to be nothing but extensible field (the "Key" field repeats) which may be the only object like this, and therefore some swig macro might be trying to locate the Output_DiagnosticFields which is empty.

**Comment by jmarrec** [comment]
This is just because the Output:Diagnostic object already existed in the IDD, so previous passes of csharp generated sources for Output_DiagnosticFields.hxx. Clean rebuild fixes this.

FYI @tijcolem before or shortly after merging this one, need to wipe out build dir on Windows

**Comment by tijcolem** [comment]
@jmarrec  Build contents on Windows CI has been removed.  Re-running CI job.

**Comment by jmarrec** [comment]
Thanks @tijcolem. So windows built fine as expected. Seems like there's a problem with EnergyPlusFixture.ForwardTranslator_OutputDebuggingData" that I need to fix

**Pull request merged**
