### PR TITLE
Jmarrec merge

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by macumber** [comment]
You are our hero @jmarrec!

**Comment by jmarrec** [comment]
oops, I wasn't done with the ELCD and StorageConverter work. Mostly I need to create the StorageConverter class and to make sure everything is working with the ELCD. I was planning to do that asap over the last two weeks, but I've been swamped lately.

**Comment by macumber** [comment]
That's cool, I wanted to get most of this stuff in now while we are in the beginning of a release cycle, also before some work to add fuel cells.  Can you make a new branch off of current develop to add any new changes?

**Pull request merged**
