### PR TITLE
Fix set methods that require an OptionalDouble

### PR DESCRIPTION
**Pull request by jmarrec**
Fixes issue #2054

### CODE REVIEW

**Comment by jmarrec** [comment]
I didn't try to do a build to check if I didn't make a mistake, I feel like blowing my brains off right now (I did the hpp and Impl_hpp mods using a python script, but for the cpp I went in manually, it was NOT nice)

**Comment by macumber** [comment]
:thumbsup:

**Comment by nrel-bot-3** [comment]
@kbenne @jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
