### PR TITLE
Addresses #4329 and #4330, issues with AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass

### LINKED ISSUE #4329: Air nodes not set for Coil:Cooling:DX:TwoStageWithHumidityControlMode on AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass
Issue overview
--------------
The EnergyPlus object AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass accepts the following coil types: 
```
   A14, \field Cooling Coil Object Type
        \required-field
        \type choice
        \key Coil:Cooling:DX:SingleSpeed
        \key Coil:Cooling:DX:VariableSpeed
        \key CoilSystem:Cooling:DX:HeatExchangerAssisted
        \key Coil:Cooling:DX:TwoStageWithHumidityControlMode
        \note Specify the type of cooling coil used in this unitary system.
```

The OpenStudio SDK will accept a Coil:Cooling:DX:TwoStageWithHumidityControlMode on an AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass, but on forwardtranslation the coil 'Air Inlet/Outlet Node Name' fields will be blank, causing a Fatal simulation error. 

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
fan = FanConstantVolume.new(m)
hc = CoilHeatingGas.new(m)
cc = CoilCoolingDXTwoStageWithHumidityControlMode.new(m)
unitary = AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.new(m, fan, cc, hc)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)

puts ws.getObjectsByType("Coil_Cooling_DX_TwoStageWithHumidityControlMode".to_IddObjectType)
```
=> 
```
Coil:Cooling:DX:TwoStageWithHumidityControlMode,
  Coil Cooling DX Two Stage With Humidity Control Mode 1, !- Name
  ,                                       !- Availability Schedule Name
  ,                                       !- Air Inlet Node Name
  ,                                       !- Air Outlet Node Name
  0,                                      !- Crankcase Heater Capacity {W}
  10,                                     !- Maximum Outdoor Dry-Bulb Temperature for Crankcase Heater Operation {C}
  2,                                      !- Number of Capacity Stages
  1,                                      !- Number of Enhanced Dehumidification Modes
  CoilPerformance:DX:Cooling,             !- Normal Mode Stage 1 Coil Performance Object Type
  Coil Performance DX Cooling 1,          !- Normal Mode Stage 1 Coil Performance Name
  CoilPerformance:DX:Cooling,             !- Normal Mode Stage 1+2 Coil Performance Object Type
  Coil Performance DX Cooling 2,          !- Normal Mode Stage 1+2 Coil Performance Name
  CoilPerformance:DX:Cooling,             !- Dehumidification Mode 1 Stage 1 Coil Performance Object Type
  Coil Performance DX Cooling 3,          !- Dehumidification Mode 1 Stage 1 Coil Performance Name
  CoilPerformance:DX:Cooling,             !- Dehumidification Mode 1 Stage 1+2 Coil Performance Object Type
  Coil Performance DX Cooling 4,          !- Dehumidification Mode 1 Stage 1+2 Coil Performance Name
  ,                                       !- Supply Water Storage Tank Name
  ,                                       !- Condensate Collection Water Storage Tank Name
  -25,                                    !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}
  0,                                      !- Basin Heater Capacity {W/K}
  2;                                      !- Basin Heater Setpoint Temperature {C}
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.2.0+e11f0a08b2

### LINKED ISSUE #4330: AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass does not accept a Coil:Cooling:DX:VariableSpeed
Issue overview
--------------
Related to https://github.com/NREL/OpenStudio/issues/4329
The EnergyPlus object AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass accepts the following coil types:
```
   A14, \field Cooling Coil Object Type
        \required-field
        \type choice
        \key Coil:Cooling:DX:SingleSpeed
        \key Coil:Cooling:DX:VariableSpeed
        \key CoilSystem:Cooling:DX:HeatExchangerAssisted
        \key Coil:Cooling:DX:TwoStageWithHumidityControlMode
        \note Specify the type of cooling coil used in this unitary system.
```

However the OpenStudio SDK won't allow that object to be created with a Coil:Cooling:DX:VariableSpeed. Trying to do so produces a RuntimeError.

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
fan = FanConstantVolume.new(m)
hc = CoilHeatingGas.new(m)
cc = CoilCoolingDXVariableSpeed.new(m)
unitary = AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.new(m, fan, cc, hc)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)

puts ws.getObjectsByType("Coil_Cooling_DX_VariableSpeed".to_IddObjectType)
```
==> 
```
[openstudio.model.AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass] <2> Unable to set cooling coil
Traceback (most recent call last):
        2: from cobp_cctshcm.rb:9:in `<main>'
        1: from cobp_cctshcm.rb:9:in `new'
cobp_cctshcm.rb:9:in `initialize': D:\\OSN\\src\\model\\AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.cpp@677 : Unable to set cooling coil (RuntimeError)
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.2.0+e11f0a08b2

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4329. Fixes #4330.
 - Heating coils:
   - `CoilHeatingDXSingleSpeed` ✔️
   - `CoilHeatingDXVariableSpeed` ✔️
   - `CoilHeatingGas` ✔️
   - `CoilHeatingElectric` ✔️
   - `CoilHeatingWater` ✔️
   - `CoilHeatingSteam` ✔️ but N/A since not implemented in model/
   - `CoilHeatingDesuperheater` ❌
   - `CoilHeatingWaterToAirHeatPumpEquationFit` ❌
 - Cooling coils:
   - `CoilCoolingDXSingleSpeed` ✔️
   - `CoilCoolingDXVariableSpeed` ✔️
   - `CoilSystemCoolingDXHeatExchangerAssisted` ✔️
   - `CoilCoolingDXTwoStageWithHumidityControlMode` ✔️
   - `CoilCoolingDXTwoSpeed` ❌
   - `CoilCoolingWater` ❌
   - `CoilCoolingWaterToAirHeatPumpEquationFit` ❌
 - Functional tests at: https://github.com/NREL/OpenStudio-resources/pull/143.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Review by jmarrec — CHANGES_REQUESTED** [review]

**Review by jmarrec — APPROVED** [review]

**Comment by jmarrec** [comment]
Made a couple of changes to the unit test mostly. Will let CI churn, then merge. Nice job @joseph-robertson !

**Comment by jmarrec** [comment]
ctest failures are unrelated to this PR. @tijcolem We need to wipe the build tree on the increment runner and rebuild following the merge of #4349

**Comment by jmarrec** [comment]
I'm respawing windows (again) since I think the build directory has been externally wiped while it was running.

**Comment by joseph-robertson** [comment]
@jmarrec Any idea why, e.g., `CoilHeatingDesuperheater` or `CoilHeatingWaterToAirHeatPumpEquationFit` were originally handled in the ft if the idd didn't permit them? It's ok to remove support for them in the ft, right?

**Comment by jmarrec** [comment]
> Any idea why, e.g., `CoilHeatingDesuperheater` or `CoilHeatingWaterToAirHeatPumpEquationFit` were originally handled in the ft if the idd didn't permit them? It's ok to remove support for them in the ft, right?

@joseph-robertson That was done 7 years ago. My guess was that it was added in case the VAVChangeoverbypass would be extended to support these. The source code is definitive though:

https://github.com/NREL/EnergyPlus/blob/8579d29ad43d923b97a3e2095bf9cfb3fe4e2136/src/EnergyPlus/HVACUnitaryBypassVAV.cc#L695-L698

https://github.com/NREL/EnergyPlus/blob/8579d29ad43d923b97a3e2095bf9cfb3fe4e2136/src/EnergyPlus/HVACUnitaryBypassVAV.cc#L903-L908

**Pull request merged**
