### PR TITLE
2097 ep 8 5

### PR DESCRIPTION
**Pull request by kbenne**
This is the E+ 8.5 update. 

All of the simulations tests (that are expected to pass) do pass.

There are some unit test failures. I have fixed a bunch. Here is what is left. Anyone care to examine. Some of these I hear are intentional. The path ones have been failing on mac for a while. 

The following tests FAILED:
```
	 27 - IddFixture.IddFactory_Units (Failed)
	 40 - IdfFixture.IdfFile_UnixLineEndings (Failed)
	 41 - IdfFixture.IdfFile_MixedLineEndings (Failed)
	 42 - IdfFixture.IdfFile_DosLineEndings (Failed)
	 43 - IdfFixture.IdfFile_ObjectComments (Failed)
	163 - SqlFileFixture.AnnualTotalCosts (Failed)
	204 - CoreFixture.Path_toString (Failed)
	212 - CoreFixture.IsNetworkPath (Failed)
	493 - BCLFixture.BCLComponent (Failed)
	495 - BCLFixture.BCLMeasure (Failed)
	1942 - EnergyPlusFixture.ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted (Failed)
	1947 - EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_Hourly_Shifted (Failed)
	1949 - EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_500_Shifted (Failed)
	2095 - RunManagerTestFixture.ModelToRadJob (Failed)
	2105 - RunManagerTestFixture.RelocateDaylightSimPath (SEGFAULT)
	2149 - AnalysisFixture.PatExportRun (Failed)
	2235 - AnalysisDriverFixture.DesignOfExperiments_MeshAnalysis (Timeout)
	2236 - AnalysisDriverFixture.PostProcessJobs_PostProcessSecondXML (Timeout)
	2301 - RubyTest-DaylightSim_Test-DaylightSim_genannual (Failed)
	2302 - RubyTest-ModelToRad_Test-ModelToRad (Failed)
	2303 - RubyTest-ModelToRad_Test-ModelToRad_Blinds (Failed)
	2304 - RubyTest-ModelToRad_Test-ModelToRad_FrameAndDivider (Failed)
	2307 - RubyTest-PATMeasures_Test-PATMeasures (Failed)
	2308 - RubyTest-PATMeasures_Test-NewMeasures (Failed)
	2362 - RubyTest-PathWatcher_Test-watchFile (Failed)
	2363 - RubyTest-PathWatcher_Test-watchDir (Failed)
```

Interestingly when I compare to develop tests I see even more test failures.

	  2 - IddFixture.OSIddFile (Failed)
	 21 - IddFixture.IddFactory_Version_Header (Failed)
	 22 - IddFixture.IddFactory_IddFile (Failed)
	 23 - IddFixture.IddFactory_isInFile (Failed)
	 24 - IddFixture.IddFactory_IddObjects (Failed)
	 43 - IdfFixture.IdfFile_ObjectComments (Failed)
	 46 - IdfFixture.IdfObject_ConstructFromText_Comments (Failed)
	136 - IdfFixture.WorkspaceObject_Filter_Sources (Failed)
	163 - SqlFileFixture.AnnualTotalCosts (Failed)
	204 - CoreFixture.Path_toString (Failed)
	212 - CoreFixture.IsNetworkPath (Failed)
	214 - CoreFixture.PathWatcher_Dir (Failed)
	486 - BCLFixture.RemoteBCLTest (OTHER_FAULT)
	487 - BCLFixture.RemoteBCLTest2 (OTHER_FAULT)
	488 - BCLFixture.GetComponentByUID (Failed)
	489 - BCLFixture.RemoteBCLMetaSearchTest (OTHER_FAULT)
	490 - BCLFixture.BCLXML (OTHER_FAULT)
	491 - BCLFixture.BCLXML_New (OTHER_FAULT)
	492 - BCLFixture.BCLComponent (Failed)
	494 - BCLFixture.BCLMeasure (OTHER_FAULT)
	495 - BCLFixture.BCLMeasure_CTor (OTHER_FAULT)
	496 - BCLFixture.PatApplicationMeasures (SEGFAULT)
	501 - ModelFixture.AirLoopHVACOutdoorAirSystem_controllerOutdoorAir (Failed)
	502 - ModelFixture.AirLoopHVACOutdoorAirSystem_clone (Failed)
	775 - Connection.Name (Failed)
	1008 - ModelFixture.MeterFromModel (Failed)
	1078 - ModelFixture.PlantLoop_supplyComponents (Failed)
	1820 - ModelFixture.ZoneHVACLowTemperatureRadiantElectric_Check_Constructor (Failed)
	1831 - ModelFixture.ZoneHVACUnitHeater_Check_Constructor (Failed)
	1937 - EnergyPlusFixture.ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted (Failed)
	1942 - EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_Hourly_Shifted (Failed)
	1944 - EnergyPlusFixture.ForwardTranslator_ScheduleVariableInterval_500_Shifted (Failed)
	2043 - RulesetFixture.UserScript_EmbeddedRubyTest (OTHER_FAULT)
	2090 - RunManagerTestFixture.ModelToRadJob (Failed)
	2096 - RunManagerTestFixture.UserScriptJobMerging (OTHER_FAULT)
	2097 - RunManagerTestFixture.BCLMeasureRubyScript (OTHER_FAULT)
	2098 - RunManagerTestFixture.BCLMeasureRubyScriptEPWPathUnmerged (OTHER_FAULT)
	2099 - RunManagerTestFixture.BCLMeasureRubyScriptEPWPath (OTHER_FAULT)
	2100 - RunManagerTestFixture.RelocateDaylightSimPath (SEGFAULT)
	2139 - AnalysisFixture.Analysis_ClearAllResults (OTHER_FAULT)
	2140 - AnalysisFixture.Analysis_JSONSerialization_PreRun_Roundtrip (OTHER_FAULT)
	2141 - AnalysisFixture.Analysis_JSONSerialization_Versioning (OTHER_FAULT)
	2142 - AnalysisFixture.Analysis_JSONSerialization_Analysis2_Simulate_Roundtrip (OTHER_FAULT)
	2143 - AnalysisFixture.Analysis_JSONSerialization_Analysis2_NoSimulate_Roundtrip (OTHER_FAULT)
	2144 - AnalysisFixture.PatExportRun (Failed)
	2147 - AnalysisFixture.Problem_FileTypesAreCompatible_NewMeasureGroup (SEGFAULT)
	2148 - AnalysisFixture.Problem_FileTypesAreCompatible_ExistingMeasureGroup (SEGFAULT)
	2149 - AnalysisFixture.Problem_UpdateMeasure_MeasureGroups (OTHER_FAULT)
	2172 - AnalysisFixture.DataPoint_JSONSerialization_PreRun_Roundtrip (OTHER_FAULT)
	2173 - AnalysisFixture.DataPoint_JSONSerialization_PostRun_Roundtrip (OTHER_FAULT)
	2174 - AnalysisFixture.DataPoint_JSONSerialization_Versioning (OTHER_FAULT)
	2175 - AnalysisFixture.DataPoint_Selected (OTHER_FAULT)
	2178 - AnalysisFixture.DDACEAlgorithmOptions (OTHER_FAULT)
	2179 - AnalysisFixture.DDACEAlgorithm_CompatibleProblemType (OTHER_FAULT)
	2186 - AnalysisFixture.RubyMeasure_BCLMeasure (OTHER_FAULT)
	2211 - ProjectFixture.ProjectDatabaseRecord (Failed)
	2214 - ProjectFixture.RubyMeasureRecord_BCLMeasure (SEGFAULT)
	2217 - ProjectVersioningFixture.Versioning_OnOpen (Failed)
	2218 - ProjectVersioningFixture.Versioning_OnConstruction (Failed)
	2227 - AnalysisDriverFixture.RuntimeBehavior_StopCustomAnalysis (Timeout)
	2229 - AnalysisDriverFixture.DataPersistence_DataPointErrors (OTHER_FAULT)
	2230 - AnalysisDriverFixture.DesignOfExperiments_MeshAnalysis (Timeout)
	2231 - AnalysisDriverFixture.PostProcessJobs_PostProcessSecondXML (Timeout)
	2232 - AnalysisDriverFixture.PostProcessJobs_OpenStudioPostProcessAndResponses (Timeout)
	2236 - AnalysisDriverFixture.SimpleProject_InsertMeasure (OTHER_FAULT)
	2237 - AnalysisDriverFixture.SimpleProject_UpdateMeasure (OTHER_FAULT)
	2238 - AnalysisDriverFixture.SimpleProject_NonPATToPATProject (OTHER_FAULT)
	2239 - AnalysisDriverFixture.SimpleProject_EditProblemWithTwoWorkflows (OTHER_FAULT)
	2241 - AnalysisDriverFixture.SimpleProject_AnalysisFixUpOfFilePaths (OTHER_FAULT)
	2256 - OpenStudioLibFixture.IconLibrary_Icon (Failed)
	2257 - OpenStudioLibFixture.IconLibrary_MiniIcon (Failed)
	2296 - RubyTest-DaylightSim_Test-DaylightSim_genannual (Failed)
	2297 - RubyTest-ModelToRad_Test-ModelToRad (Failed)
	2298 - RubyTest-ModelToRad_Test-ModelToRad_Blinds (Failed)
	2302 - RubyTest-PATMeasures_Test-PATMeasures (Failed)
	2303 - RubyTest-PATMeasures_Test-NewMeasures (Failed)
	2357 - RubyTest-PathWatcher_Test-watchFile (Failed)
	2358 - RubyTest-PathWatcher_Test-watchDir (Failed)

### CODE REVIEW

**Comment by macumber** [comment]
@kbenne are you running your tests in parallel?  That can cause some failures that you don't see in sequential testing.  I usually build the Experimental target to test

**Comment by kbenne** [comment]
@macumber you're right I am. And I have seen parallel test failures. 

Anyway I have one more commit coming for you in particular that will include a windows E+ package.

**Comment by kbenne** [comment]
@macumber I'm done now. All E+ builds have been uploaded to s3 and checksums have been committed to OS code.

Ready for merge.

**Comment by macumber** [comment]
@kbenne getting to this tonight :-/

**Comment by macumber** [comment]
I am most concerned about these failures:

```
IddFixture.IddFactory_Units (Failed)
IdfFixture.IdfFile_UnixLineEndings (Failed)
IdfFixture.IdfFile_MixedLineEndings (Failed)
IdfFixture.IdfFile_DosLineEndings (Failed)
IdfFixture.IdfFile_ObjectComments (Failed)
```

**Comment by macumber** [comment]
IddFixture.IddFactory_Units is failing because it can't parse units in:

```
Pump:VariableSpeed field: Design Shaft Power per Unit Flow Rate per Unit Head
\units W/((m3/s)-Pa)
\ip-units W/((gal/min)-ftH20)
```
I suggest we remove these units from the ProposedE+.idd, what do you think @kbenne ?

**Comment by macumber** [comment]
IdfFixture.IdfFile_UnixLineEndings (Failed)
IdfFixture.IdfFile_MixedLineEndings (Failed)
IdfFixture.IdfFile_DosLineEndings (Failed)
IdfFixture.IdfFile_ObjectComments (Failed)

are failing because version translator inserted some extra lines that broke up comments and their objects.  These files all got checked out with Windows line endings (due to our gitattributes) so I don't think they are testing what we want them to any more.  I suggest commenting out the tests, what do you think @kbenne ?

**Comment by macumber** [comment]
I need to fix these later (but before 1.11.0)

```
RunManagerTestFixture.JobStatePersistence_NoErrors
RunManagerTestFixture.JobStatePersistence_Errors
RunManagerTestFixture.JobStatePersistence_Uncompleted
```

**Comment by macumber** [comment]
The PAT Measures tests take too long and are not passing, those need to get fixed too

**Pull request merged**
