### PR TITLE
Fix #4847 - OpenStudio logging behaves differently on Windows/Linux

### LINKED ISSUE #4847: OpenStudio logging singleton issues (especially on Windows) when using interpreted bindings (ruby measures)
Issue overview
--------------

Two issues observed comparing the behavior of OpenStudio logging between Linux and Windows:

1. Windows produces more warning messages than appear on Linux. Why?! I primarily do my testing on Linux, so I'm concerned that I might be missing things.

```patch
--- C:/Users/shorowit/Desktop/Linux.txt	Thu Mar 30 15:24:05 2023
+++ C:/Users/shorowit/Desktop/Windows.txt	Thu Mar 30 15:23:57 2023
@@ -3,2 +3,5 @@
 [openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.EpwFile] <0> Successive data points (1995-Jan-31 to 1994-Feb-01, ending on line 753) are greater than 1 day apart in EPW file 'C:/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw'. Data will be treated as typical (TMY)
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Running simulation...
@@ -8,2 +11,6 @@
 [openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Wrote output file: run/results_annual.csv.
```

2. When using `OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Fatal)` to suppress warning messages, warnings are completely suppressed on Linux but not on Windows. For some of our workflows, this means we can get dozens and dozens of lines of output on Windows, which is annoying and makes it difficult to see the output of interest.

```patch
--- C:/Users/shorowit/Desktop/Linux.txt	Thu Mar 30 15:24:02 2023
+++ C:/Users/shorowit/Desktop/Windows.txt	Thu Mar 30 15:24:00 2023
@@ -2,2 +2,5 @@
 Creating input...
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.EpwFile] <0> Successive data points (1995-Jan-31 to 1994-Feb-01, ending on line 753) are greater than 1 day apart in EPW file 'C:/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw'. Data will be treated as typical (TMY)
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Running simulation...
@@ -5,2 +8,6 @@
 Processing output...
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Wrote output file: run/results_annual.csv.

```

## Expected Behavior
OpenStudio should behave the same on Linux and Windows.

## Steps to Reproduce
1. Clone https://github.com/NREL/OpenStudio-HPXML
2. To reproduce issue 1, run `openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml -o test` on Windows and Linux.
3. To reproduce issue 2, comment out [this line](https://github.com/NREL/OpenStudio-HPXML/blob/4f39a733f647d7b7366b176bc66925845b91de20/HPXMLtoOpenStudio/resources/meta_measure.rb#L15) and run the above command again on Windows and Linux.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Windows 10 and Ubuntu 20.04 (WSL)
 - OpenStudio 3.5

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4847

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
Before fix at https://github.com/NREL/OpenStudio/pull/4852/commits/5d61bc74b274f0ab3830436080e0feed856d3ce1 we get the windows error in action, see log https://ci.openstudio.net/blue/organizations/jenkins/openstudio-incremental-windows/detail/PR-4852/3/pipeline#step-61-log-8

```shell
Running: D:\git\OpenStudio\build\Products\openstudio.exe execute_ruby_script D:\git\OpenStudio\src\cli\test\logger_test.rb

0 [test] <0> Warn
1 [test] <1> Error
2 [test] <1> Error
3 LOGGER - STDOUT Warn
4 [test] <1> Error
5 LOGGER - STDOUT Warn
6 LOGGER - STDOUT Error

Traceback (most recent call last):
  File "D:/git/OpenStudio/src/cli/test/run_test_logger.py", line 54, in <module>
    raise IOError(f"Expected 3 lines, got {n}")
OSError: Expected 3 lines, got 7


2/2 Test #3637: OpenStudioCLI.Labs.test_logger_rb ...***Failed    1.08 sec

Namespace(labs=True, logger_file=WindowsPath('D:/git/OpenStudio/src/cli/test/logger_test.rb'), os_cli_path=WindowsPath('D:/git/OpenStudio/build/Products/openstudio.exe'))

Running: D:\git\OpenStudio\build\Products\openstudio.exe labs execute_ruby_script D:\git\OpenStudio\src\cli\test\logger_test.rb

0 [test] <0> Warn
1 [test] <1> Error
2 [test] <1> Error
3 LOGGER - STDOUT Warn
4 LOGGER - STDOUT Error

Traceback (most recent call last):
  File "D:/git/OpenStudio/src/cli/test/run_test_logger.py", line 54, in <module>
    raise IOError(f"Expected 3 lines, got {n}")
OSError: Expected 3 lines, got 5
```

**Comment by shorowit** [comment]
I can't speak to the correctness of the implementation, but I tried this out on Windows and Ubuntu, and they both gave the desired result. So I can confirm that this fixes the issue.

**Comment by shorowit** [comment]
Although I noticed that when I run the CLI using `labs` on Windows, it doesn't work. Not sure if that's specific to this PR.

On Windows, first command (without labs) is successful, second command (with labs) is **not**:

image

On Ubuntu, it works both with and without labs:

image

**Comment by shorowit** [comment]
@jmarrec @tijcolem I tried the Windows labs command using build 5eaa0d8ebb and the same issue occurs there. So it's not caused by this PR. I'll see if I can find when it started failing.

**Comment by shorowit** [comment]
Found the bug, see https://github.com/NREL/OpenStudio/issues/4856.

**Pull request merged**
