### PR TITLE
Fix #3257 - zone load distribution scheme

### LINKED ISSUE #3257: ZoneHVACEquipmentList object's Load Distribution Scheme not wrapped
ZoneHVAC:EquipmentList,
       \extensible:4 Duplicate the four fields Zone Equipment Object Type through Heating Priority
       \memo List equipment in simulation order.  Note that an ZoneHVAC:AirDistributionUnit or
       \memo AirTerminal:SingleDuct:Uncontrolled object must be listed in this statement if there is a forced
       \memo air system serving the zone from the air loop.
       \memo Equipment is simulated in the order specified by Zone Equipment Cooling Sequence and
       \memo Zone Equipment Heating or No-Load Sequence, depending on the thermostat request.
       \memo For equipment of similar type, assign sequence 1 to the first system intended to
       \memo serve that type of load.  For situations where one or more equipment types has limited capacity or
       \memo limited control, order the sequence so that the most controllable piece of equipment runs last.
       \memo For example, with a dedicated outdoor air system (DOAS), the air terminal for the DOAS
       \memo should be assigned Heating Sequence = 1 and Cooling Sequence = 1.  Any other equipment should
       \memo be assigned sequence 2 or higher so that it will see the net load after the DOAS air is added
       \memo to the zone.
       \min-fields 6
  A1 , \field Name
       \required-field
       \reference ZoneEquipmentLists
  A2 , \field Load Distribution Scheme
       \type choice
       \key SequentialLoad
       \key UniformLoad
       \key UniformPLR
       \key SequentialUniformPLR
       \default SequentialLoad
  A3 , \field Zone Equipment 1 Object Type
       \begin-extensible
       \type choice
       \key ZoneHVAC:TerminalUnit:VariableRefrigerantFlow
       \key ZoneHVAC:AirDistributionUnit
       \key AirTerminal:SingleDuct:Uncontrolled
       \key ZoneHVAC:EnergyRecoveryVentilator
       \key ZoneHVAC:EvaporativeCoolerUnit
       \key ZoneHVAC:HybridUnitaryHVAC
       \key ZoneHVAC:ForcedAir:UserDefined
       \key ZoneHVAC:FourPipeFanCoil
       \key ZoneHVAC:OutdoorAirUnit
       \key ZoneHVAC:PackagedTerminalAirConditioner
       \key ZoneHVAC:PackagedTerminalHeatPump
       \key ZoneHVAC:UnitHeater
       \key ZoneHVAC:UnitVentilator
       \key ZoneHVAC:VentilatedSlab
       \key ZoneHVAC:WaterToAirHeatPump
       \key ZoneHVAC:WindowAirConditioner
       \key ZoneHVAC:Baseboard:RadiantConvective:Electric
       \key ZoneHVAC:Baseboard:RadiantConvective:Water
       \key ZoneHVAC:Baseboard:RadiantConvective:Steam
       \key ZoneHVAC:CoolingPanel:RadiantConvective:Water
       \key ZoneHVAC:Baseboard:Convective:Electric
       \key ZoneHVAC:Baseboard:Convective:Water
       \key ZoneHVAC:HighTemperatureRadiant
       \key ZoneHVAC:LowTemperatureRadiant:VariableFlow
       \key ZoneHVAC:LowTemperatureRadiant:ConstantFlow
       \key ZoneHVAC:LowTemperatureRadiant:Electric
       \key ZoneHVAC:Dehumidifier:DX
       \key ZoneHVAC:IdealLoadsAirSystem
       \key ZoneHVAC:RefrigerationChillerSet
       \key Fan:ZoneExhaust
       \key WaterHeater:HeatPump:PumpedCondenser
       \key WaterHeater:HeatPump:WrappedCondenser
       \key HeatExchanger:AirToAir:FlatPlate
       \key AirLoopHVAC:UnitarySystem
       \required-field
  A4 , \field Zone Equipment 1 Name
       \required-field
       \type object-list
       \object-list ZoneEquipmentNames
  N1 , \field Zone Equipment 1 Cooling Sequence
       \required-field
       \type integer
       \minimum 1
       \note Specifies the zone equipment simulation order
       \note when the zone thermostat requests cooling
  N2 ; \field Zone Equipment 1 Heating or No-Load Sequence
       \required-field
       \type integer
       \minimum 1
       \note Specifies the zone equipment simulation order
       \note when the zone thermostat requests heating or no load

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #3257.

### CODE REVIEW

**Comment by jmarrec** [comment]
@joseph-robertson sorry for middling (got here from https://github.com/NREL/OpenStudio-resources/pull/53), but I'm pretty sure you need to write a VersionTranslation routine, because even though it has a default, you *inserted* an IDD field. See https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/osversion/VersionTranslator.cpp#L4005

You'll need to wrap it in a `VersionTranslator::update_2_6_1_to_2_6_2`

**Comment by joseph-robertson** [comment]
@jmarrec Yep, you're right. I will do that.

**Comment by jmarrec** [comment]
@joseph-robertson As stated in https://github.com/NREL/OpenStudio-resources/pull/53#issuecomment-421323152,

Here's a FT test that you could add to `./openstudiocore/src/energyplus/Test/ThermalZone_GTest.cpp`. Note that I didn't actually test it, so you might have to do a couple of quick tweaks:

Add the following includes:

```
#include "../../model/FanZoneExhaust.hpp"
#include <utilities/idd/ZoneHVAC_EquipmentList_FieldEnums.hxx>
```

At end of file:

```
TEST_F(EnergyPlusFixture,ForwardTranslator_LoadDistributionScheme)
{
  Model model;

  Point3dVector points;
  points.push_back(Point3d(0, 0, 0));
  points.push_back(Point3d(0, 1, 0));
  points.push_back(Point3d(1, 1, 0));
  points.push_back(Point3d(1, 0, 0));

  SpaceType spaceType(model);
  spaceType.setLightingPowerPerFloorArea(1);

  ThermalZone zone(model);

  Space space1(model);
  space1.setThermalZone(zone);
  space1.setSpaceType(spaceType);


  Surface surface1(points, model);
  surface1.setSpace(space1);

  FanZoneExhaust fan(model);
  fan.addToThermalZone(zone);
  zone.setLoadDistributionScheme("UniformLoad");

  ForwardTranslator trans;
  Workspace workspace = trans.translateModel(model);

  EXPECT_EQ(1u, workspace.getObjectsByType(IddObjectType::Zone).size());
  WorkspaceObjectVector idfObjs = workspace.getObjectsByType(IddObjectType::ZoneHVAC_EquipmentList);
  EXPECT_EQ(1u, idfObjs.size());
  WorkspaceObject idf_eqlist(idfObjs[0]);
 
  EXPECT_EQ("UniformLoad", idf_eqlist.getString(ZoneHVAC_EquipmentListFields::LoadDistributionScheme));
}

```

**Comment by jmarrec** [comment]
@macumber, The FT test seems to have been added after you merged the #3271, can you pull Joseph's latest in develop too?

**Comment by macumber** [comment]
@jmarrec are you referring to this commit? https://github.com/NREL/OpenStudio/pull/3262/commits/965590c8f9201f76c2f4ebbb03fd1d98d46e0c82

**Comment by jmarrec** [comment]
Yes @macumber

**Pull request merged**
