### PR TITLE
Qwt update

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@axelstudios I think this is ready to merge.  However, it needs some serious testing and comparison with the old resultsviewer

@asparke2 @DavidGoldwasser could you guys help with that once this is merged?

**Comment by macumber** [comment]
Hmm wait, looks like results viewer has some extra stuff going on

**Comment by macumber** [comment]
I think we can deprecate the following utilities sub-libraries but I am not going to do that now:

utilities\plot
utilities\math
utilities\economics

**Comment by macumber** [comment]
@axelstudios assigning to you to do the pull, would like to get this in 1.6.3 for testing

**Comment by axelstudios** [comment]
Built and tested on mac

**Pull request merged**
