### PR TITLE
Cppcheck: add a github workflow and fix all warnings

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Following on #4139 's footsteps (which enabled clang-format), this PR adds a cppcheck github worklow, and fixes all warnings that needed fixing and silence a bunch, so that there is no warning left and we can actually **enforce** a clean cppcheck result on each PR.

I suppose we will need to modify the workflow to only run on changed files if it takes too long, but we'll see once the workflow runs (it needs to be on develop first)

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by tijcolem** [comment]
This is really awesome to see both clang-format and cppcheck running now! 
Looks like there is a new unit test failure: 

```
 RUN      ] Date.StringConstructor_v2
[utilities.time.Date] <2> Failed to parse a valid date from '20050111'
/srv/jenkins/openstudio/git/incremental/OpenStudio/src/utilities/time/Test/Date_GTest.cpp:107: Failure
```


Seems to be a parsing issue. clang-format is flagging this file as well so could be related. 

Also, I see that the clang-format is version 9 on bionic image using GitHub actions. I'll try and install version 11 or higher as this is the preferred version and there can be slight differences in results when running clang-format versions. I might even be able to use the new ubuntu 20.04 image if that ships with a newer version of clang-format.  I'll find out.

**Comment by jmarrec** [comment]
@tijcolem Date::Date(std::string) is one file where I actually made a change of behavior. There was a warning about m_baseYear and m_assumedBaseYear not being assigned in tbe Ctor and when unable to parse something it was actually doing that silently and using an impl (boost::gregorian::date) that is not_a_date and so calling year() on it would have boost throwing later on. I guessed I messed up something, I will address it shortly

**Comment by tijcolem** [comment]
@jmarrec Looks good to me! I can do another squash and merge on this unless there are specific commits that you need to be able to reference later?  I'll also update the .git-blame-ignore-revs with sha.

**Comment by jmarrec** [comment]
@tijcolem I went ahead and squashed the branch into two commits : all cppcheck changes, and separately the `Date::Date(const std::string&)` change since I fixed the cppcheck warning and also made behavioral changes: it'll be useful to be able to single this change out. I also added a commit to gitblame-ignore-revs. So this is ready to merge normally.

**Review by tijcolem — APPROVED** [review]

**Pull request merged**
