### PR TITLE
86121710 window frame divider

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by asparke2** [comment]
@macumber Only one issue I can see: the default inputs for the frame and divider object aren't exported to IDF correctly.  This would be an issue if someone entered the other values, but kept the defaults b/c they looked good.

1. Create a new frame and divider via the inspector.  Notice that some of the fields have default values.  
image
2. Look at the OSM.  Default values are all blank.
```OS:WindowProperty:FrameAndDivider,
  {657d67ae-c50d-4073-821d-0569556a327f}, !- Handle
  Window Property Frame And Divider 1,    !- Name
  ,                                       !- Frame Width {m}
  ,                                       !- Frame Outside Projection {m}
  ,                                       !- Frame Inside Projection {m}
  ,                                       !- Frame Conductance {W/m2-K}
  ,                                       !- Ratio of Frame-Edge Glass Conductance to Center-Of-Glass Conductance
  ,                                       !- Frame Solar Absorptance
  ,                                       !- Frame Visible Absorptance
  ,                                       !- Frame Thermal Hemispherical Emissivity
  ,                                       !- Divider Type
  ,                                       !- Divider Width {m}
  ,                                       !- Number of Horizontal Dividers
  ,                                       !- Number of Vertical Dividers
  ,                                       !- Divider Outside Projection {m}
  ,                                       !- Divider Inside Projection {m}
  ,                                       !- Divider Conductance {W/m2-K}
  ,                                       !- Ratio of Divider-Edge Glass Conductance to Center-Of-Glass Conductance
  ,                                       !- Divider Solar Absorptance
  ,                                       !- Divider Visible Absorptance
  ,                                       !- Divider Thermal Hemispherical Emissivity
  ,                                       !- Outside Reveal Depth {m}
  ,                                       !- Outside Reveal Solar Absorptance
  ,                                       !- Inside Sill Depth {m}
  ,                                       !- Inside Sill Solar Absorptance
  ,                                       !- Inside Reveal Depth {m}
  ;                                       !- Inside Reveal Solar Absorptance
```
3. Export model to IDF.  Notice that the defaults didn't get into the IDF.
```WindowProperty:FrameAndDivider,
  Window Property Frame And Divider 1,    !- Name
  ,                                       !- Frame Width {m}
  ,                                       !- Frame Outside Projection {m}
  ,                                       !- Frame Inside Projection {m}
  ,                                       !- Frame Conductance {W/m2-K}
  ,                                       !- Ratio of Frame-Edge Glass Conductance to Center-Of-Glass Conductance
  ,                                       !- Frame Solar Absorptance
  ,                                       !- Frame Visible Absorptance
  ,                                       !- Frame Thermal Hemispherical Emissivity
  ,                                       !- Divider Type
  ,                                       !- Divider Width {m}
  ,                                       !- Number of Horizontal Dividers
  ,                                       !- Number of Vertical Dividers
  ,                                       !- Divider Outside Projection {m}
  ,                                       !- Divider Inside Projection {m}
  ,                                       !- Divider Conductance {W/m2-K}
  ,                                       !- Ratio of Divider-Edge Glass Conductance to Center-Of-Glass Conductance
  ,                                       !- Divider Solar Absorptance
  ,                                       !- Divider Visible Absorptance
  ;                                       !- Divider Thermal Hemispherical Emissivity
```

**Comment by macumber** [comment]
@asparke2 this is actually a bigger issue that I think I am coming around on.  Basically, if a user does not specify a value in OpenStudio then the OpenStudio default should be written to the IDF rather than using the E+ default.  I was previously thinking that default meant user did not supply any information so should use the simulation engines default.  However, we should the defaults in the UI so we should ensure that these get written to the IDF. 

@kbenne @DavidGoldwasser you all on board with this?

**Comment by kbenne** [comment]
Sure.  Where is the OpenStudio default defined again?  ....  Ducking for cover...

**Comment by macumber** [comment]
@kbenne sounds like you are in a laughy mood, glad you're having a good day so far :-)

**Comment by macumber** [comment]
I have a lot of code that is guilty of this... need to change it 

On translation from IDF to OpenStudio we are good to use our defaults instead of EnergyPlus's right? 

@kbenne maybe we should merge the IDDs and take an average? </snark>

**Comment by kbenne** [comment]
"On translation from IDF to OpenStudio we are good to use our defaults instead of EnergyPlus's right?"  -- yes please.

**Pull request merged**
