### PR TITLE
Fix #745 - Use the 'Year' field from Sql file

### LINKED ISSUE #745: General problems with leap year simulations

### PR DESCRIPTION
**Pull request by jmarrec**
Fix #745 - Use the 'Year' field from Sql file

Fix https://github.com/NREL/OpenStudio-measures/issues/138

### CODE REVIEW

**Comment by macumber** [comment]
Wouldn't hurt to include daylighting reports or any other timeseries data and check that those are reported correctly too.

**Comment by jmarrec** [comment]
> Wouldn't hurt to include daylighting reports or any other timeseries data and check that those are reported correctly too.

Daylight maps don't have the year field in E+ SQL yet (cf issue https://github.com/NREL/EnergyPlus/issues/7225 and PR I opened to add it https://github.com/NREL/EnergyPlus/pull/7235)

**Comment by jmarrec** [comment]
Added tests in #69. All 8 pass with this branch, versus only 1 with 2.7.1.

There's one thing that could be problematic for us actually: currently if you specify a leap year, say 2012, run period, if you pass a weather file that doesn't include Feb 29 you only get 365 days of data (and no warning in eplusout.err). 

When reading the time series back, everything would be shifted by one day for us (and it'd be probably very weird for the user to have a Feb 29 but No December 31...) ... Because we expect for it to be a leap year and we construct the timeseries given only the firstReportDateTime and incrementing intervals.

**Comment by macumber** [comment]
Cool thanks for the tests @jmarrec, seems like the leap year / epw issue should be filed with the EnergyPlus team.  And it looks like it already does https://github.com/NREL/EnergyPlus/issues/7240

**Pull request merged**
