### PR TITLE
Removing Ruleset from measure and measure test templates

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
Fixes issue #2656 had to create workflow on the fly to create runner.
Also removed 1x path for reporting measure test. Note: Measure made
based on these templates should not be back versioned in measure.xml to
1.x version of OpenStudio.

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @DavidGoldwasser @lgentile it has been 7 days since this pull request was last updated.

**Comment by DavidGoldwasser** [comment]
Update OSW to have a step, maybe pointing to used or to fake name like this.
```
{
   "created_at" : "20171204T143418Z",
   "steps" : [
      {
         "measure_dir_name" : "not_real"
      }
   ]
}
```

It avoids this error
https://github.com/NREL/OpenStudio/blob/b1d9ad7d901ceab52cafe73df430d218165540a2/openstudiocore/src/measure/OSRunner.cpp#L197

Typically this doesn't break measure test, just looks like this
```
# Running tests:

[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
**MEASURE APPLICABILITY**
0 = Success
**INITIAL CONDITION**
**FINAL CONDITION**
**INFO MESSAGES**
**WARNING MESSAGES**
**ERROR MESSAGES**
***Machine-Readable Attributes**
```

But in some cases when this standards method is called, could result in measure test failing.
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/utilities/logging.rb#L42

**Pull request merged**
