### PR TITLE
Year description results - DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
This pull request should not be merged

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Pull request closed without merging**
