### PR TITLE
Fix #4699 - E+ 22.2: ZoneHVAC:PackagedTerminal AirConditionner/HeatPump requires a supply air fan operating mode schedule

### LINKED ISSUE #4699: E+ 22.2: ZoneHVAC:PackagedTerminal AirConditionner/HeatPump requires a supply air fan operating mode schedule
Issue overview
--------------

In 22.2.0, there’s a new error in ZoneHVAC:PackagedTerminal:AC/HP if you don’t supply a Supply Air Fan Operating Mode Schedule when you have a Fan:ConstantVolume

```
   ** Severe  ** ZoneHVAC:PackagedTerminalAirConditioner = ZONE HVAC PACKAGED TERMINAL AIR CONDITIONER 4
   **   ~~~   ** Fan type must be Fan:OnOff or Fan:SystemModel when Supply Air Fan Operating Mode Schedule Name is blank
```

Except:
* if I pass a Always 0 schedule, there’s another error saying value must be > 0 for Fan:CV. 
* If I pass Always 1 schedule, my EUI changes quite dramatically. 
* If I use a Fan:OnOff with always 0, my EUI is closer but still different.

We need a way to handle this so we don't end up with too broken models (lots are failing on OS-resources right now) and ideally without changing EUI too drastically.

cf https://github.com/NREL/OpenStudio/commit/9abf9e42edbe75ab01a160f3ba61fa1dd25dea89#diff-6792272e2d22af45d561660c93bc735d74a30b2a15218ed60d1b05a91eeca176R310

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### LINKED ISSUE #4703: Broken transition rules for OS:Coil:Heating:Gas:MultiStage
Issue overview
--------------

Reg test multi_stage.osm is failing because this ends up blank: https://github.com/NREL/OpenStudio-resources/blob/7ee4b1be25a7794651e28be6836119d7d69a166e/model/simulationtests/multi_stage.osm#L1667

This is only a problem on develop, not in any release.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4699
 - Fixes #4703

#### API Break

    * `ZoneHVACPackagedTerminalAirConditioner` and `ZoneHVACPackagedTerminalHeatPump` have an API-breaking change related to its `supplyAirFanOperatingModeSchedule` getter. It is now a required field that returns `Schedule` instead of `boost::optional<Schedule>`. Method `resetSupplyAirFanOperatingModeSchedule` is also removed.
        * It is set to `alwaysOnDiscreteSchedule` (=Constant) in the Constructor if you provide a `FanConstantVolume` (This is **required** by E+)
        * It is set to `alwaysOffDiscreteSchedule` (=Cycling) in the Constructor if you provide any other fan types (E+ treats a blank schedule as always off)

#### Unusual Version Translation rules to preserve functionality and Energy Usage

    * There are unusual `VersionTranslator` Rules for Packaged Systems (PTAC or PTHP) that use a `FanConstantVolume` and that do not have a `Supply Air Fan Operating Mode Schedule`. In 22.1.0 this would effectively, and mistakenly, function as a cycling fan, but this is now disallowed in E+ 22.2.0. In order to retain a similar functionality and energy usage, the `FanConstantVolume` will be replaced by a `FanSystemModel` with an Always Off Schedule (=cycling fan, similar to a `Fan:OnOff`), mapping inputs such as pressure rise and efficiency appropriately.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
At this point the only failure I have left is the `ems_scott.osm` and it is due to ZoneMixing mapping to Spaces and EMS usage.

The EUI deviations are wild, but this is because the tests use a Fan:ConstantVolume, and before we didn't set a schedule so it was working as a cycling fan... bummer. I think I'm going to have to modify the tests / baseline lib to include a Schedule of always 1 and run all reg tests backwards in all OS version... geez.

image

**Comment by jmarrec** [comment]
I made a modification in https://github.com/NREL/OpenStudio-resources/commit/9a404befbc75a75c2021a50fe3cda632fea7f7a7 to force an Aways On Supply Air Fan Operating Mode Schedule, and rerun with OS 3.4.0, so I could exclude that.

Looks better. the Unitary_system I need to look into

image

**Comment by jmarrec** [comment]
Diff between 3.4.0 PackagedFanOpSch and 3.5.0:

image

I'm confused by the ptac_othercoils.osm one. Looking into it

**Comment by jmarrec** [comment]
I don't get why `ptac_othercoils.osm` is overusing by 30%...

**Comment by tijcolem** [comment]
"I think I'm going to have to modify the tests / baseline lib to include a Schedule of always 1 and run all reg tests backwards in all OS version... geez".   We can deal with this post release if this still needs to happen. 

So I ran regression tests on tip of develop and seeing 69 failures which I'm assuming all due to the large EUI diffs you highlighted above?

**Pull request merged**
