### PR TITLE
Pat mega branch rc

### PR DESCRIPTION
**Pull request by macumber**
Branch so @DavidGoldwasser can easily test multiple pat fixes

### CODE REVIEW

**Comment by macumber** [comment]
@DavidGoldwasser I'll let you know when this is ready

**Comment by DavidGoldwasser** [comment]
Thanks @macumber for making a common branch. I'll wait to test until I hear from you.

**Comment by macumber** [comment]
@DavidGoldwasser this is ready to go :-)

**Comment by macumber** [comment]
Check the commit log to see which bugs this fixes

https://github.com/NREL/OpenStudio/pull/2116/commits

**Pull request merged**
