### PR TITLE
Four pipe beam

### PR DESCRIPTION
**Pull request by jmarrec**
I wrapped the object `AirTerminal:SingleDuct:ConstantVolume:FourPipeBeam` in the SDK.

* I implemented too sublcasses for the cooling/heating side: `CoilCoolingFourPipeBeam` and `CoilHeatingFourPipeBeam`
* ForwardTranslator has a couple of sanity checks:
    * must be connected to an AirLoopHVAC and have at least one coil subclass that is connected to a plantLoop
    * If you have a coil (heating or cooling) and this coil is connected to a plantloop, then all three curves are required objects so I check for that too.
* Added model + forward translator Gtest
* Added icons, added to hvac_library.osm, and code added to be able to use it in OS App.
* Regression test in OpenStudio-resources was added in this commit https://github.com/jmarrec/OpenStudio-resources/commit/a1ffa10f9ae0696c21dd71ba2b0810651a541383

The only thing I didn't fully test for is the OS App behavior. I merged latest develop in, in particular so I wouldn't have the crash on hvac tab #3023, but develop is broken so it won't build.
I have doubt about whether I need to override the `remove`method. I'll have to check that once develop is fixed.

Other unplanned/side changes:
* I made all port (eg `inletPort()` methods `const`, hence the high number of files I touched.

Review assignee should probably be @kbenne, time permitting.

### CODE REVIEW

**Comment by jmarrec** [comment]
Tested in OS App, and added the actual SQL autosizedXXXX statements.

Ready for review @kbenne @macumber

**Comment by macumber** [comment]
@jmarrec @kbenne says that there are now two separate prs, one that addresses const issues and one that adds this object.  Based on his review we can merge the separate four pipe beam code but not yet the const stuff. Closing this pr, have the other prs already been opened?  The four pipe object does not seem to have been merged yet

**Comment by kbenne** [comment]
well. there are at least two different branches somewhere.

**Comment by jmarrec** [comment]
For future ref, I did split it in two:
* Four Pipe Beam only: https://github.com/jmarrec/OpenStudio/tree/FourPipeBeam_Only, which was already gotten by @macumber in #3136 (and #3137 for CI)
* Making the port (inletPort/outletPort, etc) functions `const`: https://github.com/jmarrec/OpenStudio/tree/PortConst_Only

**Pull request closed without merging**
