### PR TITLE
Disabled ability to add or remove zones with inspector

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
This should only affect the SketchUp Plugin. This is should resolve issue #1667 unless we find other causes of mal-formed thermal zones.

### CODE REVIEW

**Comment by macumber** [comment]
@DavidGoldwasser I did not want to do this in a knee jerk reaction, I think you were right that this happened because the model watchers stopped working somehow, I don't think this big hammer solution is needed

@kbenne

**Comment by kbenne** [comment]
@macumber are you suggesting this is an isolated incident and we take no action at this time?  Or can we move that initialization code to somewhere that does not depend on model watcher?

**Comment by macumber** [comment]
I don't think we should disable adding and removing zones in the inspector yet.  I do think we should figure out and fix the orphaned connection when deleting a zone in the inspector. 

What I would really like is in-app analytics that get phoned home so we know which buttons people are pushing in our apps... Then we'd know if we can kill off a particular button and we could get crash reports with call stacks

**Comment by macumber** [comment]
There are several operations where we disable the model watcher and then re-enable it later.  If someone pushes the new/remove/copy buttons in the inspector we should be able to check if the model watcher is enabled.  If it is not we should pop the plugin crashed warning.

**Comment by kbenne** [comment]
ick.  Removing zones... I don't think that is something practical without model support.  https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L1395

**Comment by macumber** [comment]
@kbenne Looks like the + button calls addObject, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model_editor/InspectorDialog.cpp#L355, which does not call stuff in the public ctor, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L2169.  I wonder if any of this could be moved into the impl ctor?  If not, I can continue to just mimic it in the watcher handler.

However, the remove and copy buttons should be calling clone, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L2169, and remove, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model_editor/InspectorDialog.cpp#L384, so I wonder what the real problem is?

**Comment by kbenne** [comment]
@macumber do we know the issue #1667 was on remove?  Could it have been incomplete add or was that ruled out?  It seems like maybe it was, I can't remember.  

The most likely thing is of course some bad equipment interactions.  Equipment was removed badly by the api or something.  (basically a bug in my code)  But I was thinking we ended up here in plugin land because the model hadn't been exposed to OS App yet.

**Comment by macumber** [comment]
@DavidGoldwasser noted an orphan connection when removing thermal zone in the inspector.  However, I get the same result doing this with the API:

irb(main):002:0> m = OpenStudio::Model::Model.new
irb(main):003:0> t = OpenStudio::Model::ThermalZone.new(m)
irb(main):004:0> t.remove
irb(main):005:0> puts m

OS:Version,
  {a8028979-32db-440a-99fb-d13cbe58ff6f}, !- Handle
  1.8.0;                                  !- Version Identifier

OS:Connection,
  {fe741d7d-6aaa-47d9-874f-4aa63603ef5c}, !- Handle
  {6cf1bac5-5a0a-464f-b4db-fdb602e61b89}, !- Name
  ,                                       !- Source Object
  11,                                     !- Outlet Port
  ,                                       !- Target Object
  2;                                      !- Inlet Port

**Comment by macumber** [comment]
@kbenne given all that, I'm inclined to add my new error trapping code but keep the new, remove, and clone buttons working

**Comment by kbenne** [comment]
I agree.

**Comment by macumber** [comment]
@DavidGoldwasser I'm assigning this pull back to you, can you merge tomorrow morning after some quick testing?

@kbenne, up to you if you want to look into the orphan connection issue

**Comment by macumber** [comment]
@kbenne I was able to cause a crash byt cloning several zones, then deleting them:

 	openstudio_model.dll!boost::assertion_failed(const char * expr, const char * function, const char * file, long line) Line 51	C++
 	openstudio_model.dll!openstudio::model::detail::ZoneHVACEquipmentList_Impl::thermalZone() Line 252	C++
 	openstudio_model.dll!openstudio::model::ZoneHVACEquipmentList::thermalZone() Line 399	C++
 	openstudio_model.dll!openstudio::model::detail::ThermalZone_Impl::zoneHVACEquipmentList() Line 1834	C++
 	openstudio_model.dll!openstudio::model::detail::ThermalZone_Impl::equipment() Line 1867	C++
>	openstudio_model.dll!openstudio::model::detail::ThermalZone_Impl::remove() Line 1410	C++
 	openstudio_utilities.dll!openstudio::WorkspaceObject::remove() Line 1269	C++
 	openstudio_modeleditor.dll!InspectorDialog::onPushButtonDelete(bool __formal) Line 384	C++
 	openstudiomodeleditor.so!_wrap_InspectorDialog_onPushButtonDelete(int argc, unsigned __int64 * argv, unsigned __int64 self) Line 9550	C++

I verified that the clone and remove model methods were being called.  I was able to reproduce in the API:

irb(main):006:0> m = OpenStudio::Model::Model.new
irb(main):007:0> t = OpenStudio::Model::ThermalZone.new(m)
irb(main):008:0> t2 = t.clone
irb(main):009:0> t2.remove
irb(main):010:0> t.remove # will crash

**Comment by kbenne** [comment]
I'm going to open a new issue for ThermalZone::clone

**Comment by macumber** [comment]
Is the orphaned connection on normal zone remove not an issue?  I honestly don't know 

irb(main):002:0> m = OpenStudio::Model::Model.new
irb(main):003:0> t = OpenStudio::Model::ThermalZone.new(m)
irb(main):004:0> t.remove
irb(main):005:0> puts m

OS:Version,
{a8028979-32db-440a-99fb-d13cbe58ff6f}, !- Handle
1.8.0; !- Version Identifier

OS:Connection,
{fe741d7d-6aaa-47d9-874f-4aa63603ef5c}, !- Handle
{6cf1bac5-5a0a-464f-b4db-fdb602e61b89}, !- Name
, !- Source Object
11, !- Outlet Port
, !- Target Object
2; !- Inlet Port

**Comment by kbenne** [comment]
Not a functional issue.  It just looks bad.  I'll file a separate issue for that.

**Comment by kbenne** [comment]
@macumber After reviewing, I think the zone::clone is the original corruption of the user model.  It is stealing the zone air node, which I believe was the original symptom.  I'll have a fix shortly.  I'll leave it up to @axelstudios the change should get into 1.8.

**Comment by axelstudios** [comment]
I'm fine with this making it in.

**Comment by DavidGoldwasser** [comment]
@macumber and @axelstudios I'm kicking off build now. I'll do basic testing and then merge to develop.

**Pull request merged**
