### PR TITLE
Merge develop into develop3

### PR DESCRIPTION
**Pull request by jmarrec**
```
git config --global diff.renames true
git config --global diff.renamelimit 0
git checkout develop3
git merge develop
# Make sure everything is up to date, and that it's clean (no changes)
yes d | git mergetool -- openstudiocore/src/openstudio_lib/
yes d | git mergetool -- openstudiocore/src/openstudio_app/
del openstudiocore/sketchup_plugin/
del openstudiocore/src/openstudio_lib/
cp -R openstudiocore/src/* src/
```

problems are in gbxml (and sdd but won't be next time). Especially gbxml/MapEnveloppe.cpp then I manually merged CMakeLists.txt as well.

### CODE REVIEW

**Comment by jmarrec** [comment]
@tijcolem These are minor things, warnings treated as error (due to /WX flag).  cf https://github.com/NREL/OpenStudio/pull/3725/commits/aaee244ba06707e8461a235d55af1b81151d262a for the first one.

I'm fixing them as I go now.

**Comment by jmarrec** [comment]
There's a C# problem too... This one is probably going to be trickier.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0101	The namespace 'OpenStudio' already contains a definition for 'SWIGTYPE_p_openstudio__model__ThermalZone' [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	13	
Error	CS0101	The namespace 'OpenStudio' already contains a definition for 'SWIGTYPE_p_openstudio__model__ThermalZone' [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	13	
Error	CS0111	Type 'SWIGTYPE_p_openstudio__model__ThermalZone' already defines a member called '.ctor' with the same parameter types [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	16	
Error	CS0111	Type 'SWIGTYPE_p_openstudio__model__ThermalZone' already defines a member called '.ctor' with the same parameter types [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	16	
Error	CS0111	Type 'SWIGTYPE_p_openstudio__model__ThermalZone' already defines a member called '.ctor' with the same parameter types [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	20	
Error	CS0111	Type 'SWIGTYPE_p_openstudio__model__ThermalZone' already defines a member called '.ctor' with the same parameter types [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	20	
Error	CS0111	Type 'SWIGTYPE_p_openstudio__model__ThermalZone' already defines a member called 'getCPtr' with the same parameter types [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	24	
Error	CS0111	Type 'SWIGTYPE_p_openstudio__model__ThermalZone' already defines a member called 'getCPtr' with the same parameter types [C:\Users\julien\Software\Others\OpenStudio\build\csharp_wrapper\OpenStudio.csproj]	csharp_sdk	C:\Users\julien\Software\Others\OpenStudio\build\csharp\generated_sources\OpenStudioModelGeometry\SWIGTYPE_p_openstudio__model__ThermalZone.cs	24	

```

**Comment by jmarrec** [comment]
I know what's going on. It's due to ZonePropertyUserViewFactorBySurfaceName (https://github.com/NREL/OpenStudio/pull/3675)

**Comment by tijcolem** [comment]
Thanks, @jmarrec!  Windows is now building. I compared unit test results with the develop3 nightly builds and there are no differences for Linux, OSX and Windows so we can go ahead and merge.

**Pull request merged**
