### PR TITLE
adds gal/min unit conversions for liquid m3/s fields

### PR DESCRIPTION
**Pull request by MatthewSteen**
#2076

### CODE REVIEW

**Comment by MatthewSteen** [comment]
@kbenne forgot to mention this one in our Slack conversation last week. Can you merge when you have a minute?

**Comment by macumber** [comment]
This looks good to me, have you tested this @MatthewSteen 

@kbenne @evanweaver can you review (just look at files not test)

**Comment by MatthewSteen** [comment]
@macumber no I didn't test these changes.

**Comment by macumber** [comment]
Oh, are you able to test them or do you not have a build system set up?  Someone needs to test this before merging

**Comment by MatthewSteen** [comment]
No build set up yet. Also a related PR #2067 was merged before testing.

**Comment by kbenne** [comment]
#2067 looked fine, and I merged it only to have it haunt me.

**Comment by MatthewSteen** [comment]
Sorry guys, I'll get a build set up before submit anything else.

**Comment by nrel-bot-2** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-2** [comment]
@kbenne @MatthewSteen @lgentile it has been 7 days since this pull request was last updated.

**Pull request closed without merging**
