### PR TITLE
Pitched roofs

### PR DESCRIPTION
**Pull request by shorowit**
Implements automated 3D geometry for gable, hip, and shed roof types from simple inputs.

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @shorowit @lgentile it has been 7 days since this pull request was last updated.

**Comment by kbenne** [comment]
@shorowit what is the story on this? It appears stale, but the work seems important. Do you still want this to be merged?

**Comment by shorowit** [comment]
As far as I know, it has never been reviewed (@macumber?) and it's ~5000 LOC. It was also my first time writing a lot of C++ code. That said, it's almost entirely standalone code so it's unlikely to affect any existing functionality. And it has a lot of unit tests.

It does have some missing features (e.g., integration with floorspaceJS), but it's probably still useful for some people as is.

**Comment by jmarrec** [comment]
@kbenne, this is the last PR to develop. I suggest merging it.

**Pull request merged**
