### PR TITLE
Ecoding commas, semicolons, and exclamation marks in IDF format.  If …

### PR DESCRIPTION
**Pull request by macumber**
…this is too much to do at Idf level we could implement it at ModelObject level instead.

### CODE REVIEW

**Comment by macumber** [comment]
@kbenne @mbadams5 would appreciate some eyes on this

**Comment by macumber** [comment]
Should this have a version translation to go with it?  I'm not sure that is even possible?

**Comment by mbadams5** [comment]
Shouldn't `[!,;]` be rejected as invalid inputs for a field? They are invalid in EnergyPlus. I know you are getting around that by encoding and then decoding those characters.

Anyways, I am curious how this will potentially affect performance. `setString()` and `name()` are both used very often internally and I would say 99.99% of the time this encoding/decoding is not needed. Also I am leery of those 3 `boost::replace_all` calls but I don't want to speculate too much without profiling.

**Comment by macumber** [comment]
I guess checking for them would be faster than replacing them but I'm not sure if that is the desired behavior.  I could check for the presence of the &# combo before doing any replacements

**Comment by mbadams5** [comment]
That would still involve the same amount of looping as just replacing them. Don't the strings already get validated or verified somewhere else? Is there some regex that they go through?

**Comment by macumber** [comment]
Fixes #2055

**Comment by macumber** [comment]
Fixes #1597

**Comment by macumber** [comment]
I took a look at this and decided I don't want to do any performance optimizations without some profiling, otherwise I'm shooting in the dark.  I would like to get this in the 1.11 release, so 1) do you think performance testing is required to merge and 2) what is the best test case for profiling?

**Comment by macumber** [comment]
@mbadams5 I think most of the validity checking happens here https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/idf/WorkspaceObject.cpp#L387

**Comment by macumber** [comment]
I could see adding additional tests to make sure that objects can point to each other by names with special characters, find objects by name works with special characters, etc.  Any specific other test cases I should add?

**Pull request merged**
