### PR TITLE
88088660 schedule editor updates

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@asparke2 this is ready for your review now, please give it some testing time before merging

**Comment by asparke2** [comment]
@macumber here's my review:

1. Getting an unhandled exception when using the "Purge unused schedules" button
2. The model.alwaysOnDiscreteSchedule type limits are called "schedule type limits 1", which then shows up in the list of limits.  Suggest changing to "OnOff"
3. When you first go to the schedules tab, the default profile page shows for the first schedule, but the line isn't plotted.  This only happens when you open the model, and before you've clicked on any schedule.  After you click any schedule, the line shows up.  Not a huge deal.
image

**Comment by macumber** [comment]
@asparke2 I can't reproduce the crash, can you email me the osm that reproduces it?

**Comment by macumber** [comment]
@asparke2 I fixed the crash and changed the name of the schedule type limits, I'll add an issue for the other stuff

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/issues/1469

**Comment by macumber** [comment]
@asparke2 this is ready to go now

**Pull request merged**
