### PR TITLE
Wrap ModelObject in more standard way to include model.getModelObject…

### PR DESCRIPTION
**Pull request by macumber**
…ByName and other methods

### CODE REVIEW

**Comment by macumber** [comment]
Need to make sure this works with C# and other bindings

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 8 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@macumber @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
