### PR TITLE
Autosizing

### PR DESCRIPTION
**Pull request by asparke2**
Adds autosizedFoo methods for each autosizable field in every object.  Adds autosize and applySizingValues for these objects, and for Model.  When called at the model level, autosize and applySizingValues operate on all objects that implement these methods themselves.

### CODE REVIEW

**Comment by asparke2** [comment]
@kbenne @macumber I added a corresponding test to openstudio-resources.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@kbenne @asparke2 @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
