### PR TITLE
Kiva Foundation Model

### PR DESCRIPTION
**Pull request by joseph-robertson**

### CODE REVIEW

**Comment by nrel-bot-3** [comment]
@joseph-robertson @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@joseph-robertson @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@joseph-robertson @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@joseph-robertson @lgentile it has been 7 days since this pull request was last updated.

**Comment by jmarrec** [comment]
I fixed the failing G_test in #2875

**Pull request merged**
