### PR TITLE
Plant loop control

### PR DESCRIPTION
**Pull request by jmarrec**
Here's a little something courtesy of EffiBEM.

Changelog:

* Added AvailabilityManagers to the hvac_library and MainRightColumnController
* Implemented a new PlantLoop "Control": view
    * queries the ForwardTranslatePlantLoopEquipmentOperationSchemes helper functions (moved to a separate header file so they can be called) to tell the plant loop type, and list the component types (cooling, heating, setpoint, uncontrolled). This should give strong hints on what the resulting automatic plantloop equipment operation scheme will look like. 
   * Implemented a drop zone for availability managers
* Implemented a drop zone for Availability Managers for AirLoopHVAC controls view

The drop zone allows reordering the AVMs:

* If you drag and drop from the library, onto the "Drag from library box": it clones the AVM into the model and adds it at the end (already the current behavior)
* If you drag and drop from an existing AVM from the list onto the "Drag from library box": it clones the already existing AVM and adds the clone at the end
* If you drag and drop from the library, onto an existing AVM: it clones it and insert it at the current priority, shifting all existing AVMs down
* If you drag and drop from the list onto another avm: it moves the dragged AVM at the priority of the current avm, shifting all other AVMs down. You can just move AVMs around to reorder the list 

This behavior should be easily adaptable for Constructions and Thermal Zone equipment (see #2946 and #1454). @evanweaver 

Another feature is that if you now click on the Schedules on the AirLoopHVAC tab or any of the AVMs in the dropzone, they are pulled on the Main right column so you can see (and modify) the objects.
One caveat to this is that it'll show you alwaysOnDiscreteSchedule too, perhaps we should protect against editing it.

here's a short gif showing the new behavior:

smaller

### CODE REVIEW

**Comment by jmarrec** [comment]
Ideally we would need actual icons for the AVMs now that they are in the OS app, for now I use a placeholder image (SPM:MixedAir). I have ideas about how they should look, but I don't really want to spend time on this.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by evanweaver** [comment]
@jmarrec this is going stale and now has conflits. I suggest you choose an assignee to encourage one of us to review it :)

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by jmarrec** [comment]
@evanweaver I didn't know I had enough juice to assign reviewers myself =)

I actually started implementing a control view for the PlantLoop primary/heating/cooling Plant Equipment Operation Schemes to be able to look at objects there + their corresponding schedules. It isn't nearly finished and I have little time. 

So I guess we could just get this AvailabilityManager part in, and I might do the rest later.

Wanna be the reviewer? I am not one very worried about the merge conflict given it's only the hvac_library.osm... I can solve the conflict for you before you review if you want me to.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Comment by nrel-bot-3** [comment]
@jmarrec @lgentile it has been 7 days since this pull request was last updated.

**Pull request merged**
