### PR TITLE
Performance benchmarks

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

This extracts some benchmarks on several branches I have. 

I'm not sure what's the most practical way to do this. Some of these benchmarks are testing variations of something, like Current , Proposed1, Proposed2. If we're comparing two builds, then we should only have 'Current' (and this will change as we do changes).

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
@kbenne @tijcolem I created an external repo at https://github.com/jmarrec/OpenStudio-benchmarks

My idea is that it would be more convenient to have it externally and just link to libopenstudiolib. It'll allow adding benchmarks at any point and test against a previous installer. Building the benchmarks is quite quick, but we could even override which libopenstudiolib.so it loads by using LD_LIBRARY_PATH.

What do you think?

**Comment by tijcolem** [comment]
@jmarrec  I built your branch and enabled the optional BUILD_BENCHMARK. All the statistics that are generated by the python driver script are really impressive!  I do like the way it's laid out now but perhaps we can expand the current script to include post-process results from the current build and a comparison build that could show differences as percentage?  We could also keep track of these stats on CI for every build and upload results to a bucket and pull from there vs having to re-run constantly.  

Also, I'd be fine with using the env LD_LIBRARY_PATH to toggle between different libopenstudiolibs.  I don't think it works on windows though?  Maybe it has some other equivalent way to load dynamic libs.  For now though, I think we are running all the perf stuff in linux so prob not an immediate concern.  

This is awesome stuff!!

**Comment by jmarrec** [comment]
@tijcolem I'm thinking it may be better to have these in an external repo (https://github.com/jmarrec/OpenStudio-benchmarks), so it's easier to add a benchmark **after**, versus having to put the benchmark in develop, then rebase your feature branch onto it so you can compare. Thoughts?

**Comment by tijcolem** [comment]
@jmarrec Following up on this. I like you idea of having this in a separate repo where we can link to different versions of libopenstudiolibs.  I created a new repo. https://github.com/NREL/OpenStudio-benchmarks.  Could you move your repo to this?

**Comment by tijcolem** [comment]
@jmarrec Also, since this will be separate from the main OpenStudio and it doesn't much to build we can take use GitHub actions https://github.com/NREL/OpenStudio-benchmarks as the driver to track performance metrics.

**Comment by jmarrec** [comment]
@tijcolem  pushed to https://github.com/NREL/OpenStudio-benchmarks

**Comment by tijcolem** [comment]
@jmarrec Thanks for moving to the new repo! I think this a good home for this so I'm going to close this.

**Pull request closed without merging**
